closed #80 controllerクラスにHSV変換する関数の追加
KatLab-MiyazakiUniv/etrobocon2019 pull request #100
Opened 2019-06-18 05:53 UTC by match97

### 変更点
controllerクラスにHSV変換する関数の追加

### 実機テストの結果（実機テストが必要な場合）
HSV変換テスト
RGB値                        HSV値
    (R,G,B)                    (H,S,V)
赤(115,10,13)             (358.3,91.3,45.1)
緑(19,63,18)               (118.7,71.4,24.7)
青(11,36,75)               (216.6,85.3,29.4)
黒(5,6,6)                     (180.0,16.7,2.4)
白(142,156,151)         (158.6,9.0,61.2)
黄(122,108,14)           (52.2,88.5,47.8)

2019-06-18 13:02 UTC, Tatsumi0000 reviewed
そもそものRGBからHSVへの変換式（公式）がわからないから，参考資料的なやつあるならそれを貼ってくれると嬉しいかも☺️

2019-06-18 13:02 UTC, Tatsumi0000 commented on src/module/api/core/Controller.cpp
> +  }
ここ
```cpp
if(max < g) max = g;
```
みたいに１行で書けるよ．

2019-06-18 13:03 UTC, Tatsumi0000 commented on src/module/api/core/Controller.cpp
> +  }
個人の好みだけど😘

2019-06-18 16:27 UTC, match97 commented on src/module/api/core/Controller.cpp
> +  }
好みに合わせました /(^^)/

2019-06-19 05:43 UTC, korosuke613 requested changes
0除算に関しては、除算を行う前に、0でないか確認して、0の場合(rgbが0,0,0)、`max+=1`みたいにすればいいと思うよ

```c++
if(max - min != 0){
  max += 1;
}
```

こんな風に

2019-06-19 05:43 UTC, korosuke613 commented on src/module/api/core/Controller.h
> +unsigned struct HsvStatus {
ごめん、俺が無知なだけかもしれないのだけど、

`unsigned struct`って何？

2019-06-19 05:43 UTC, korosuke613 commented on src/module/api/core/Controller.cpp
> +HsvStatus Controller::getHsv()
些細なことですが、戻り値を `HsvStatus` とするより `const HsvStatus&` とする方が無駄なインスタンス化を防げます。

また、好みですが、こうしたゲッターには
`HsvStatus Controller::getHsv() const`
のようにconst修飾しておく方がC++らしいです 😋 

@Tamiyas より

2019-06-19 05:43 UTC, korosuke613 commented on src/module/api/core/Controller.h
> +  HsvStatus hsv;
`hsv` の初期化をしてほしいですね。
方法としては、Controllerのコンストラクタに `hsv` のメンバーをそれぞれ初期化するコードを書くか
`HsvStatus` クラスにコンストラクタを設けることですね

@Tamiyas より

2019-06-19 05:43 UTC, korosuke613 commented on src/module/api/core/Controller.cpp
> +    hsv.hue = 60 * ((g - b) / (max - min));
黒の場合、0除算になりませんか？
正確に、RGB(0,0,0)となることは稀だろうけど

@Tamiyas より

2019-06-19 05:43 UTC, korosuke613 commented on src/module/api/core/Controller.cpp
> +    hsv.hue = 60 * ((b - r) / (max - min)) + 120;
黒の場合、0除算になりませんか？
正確に、RGB(0,0,0)となることは稀だろうけど

@Tamiyas より

2019-06-19 05:43 UTC, korosuke613 commented on src/module/api/core/Controller.cpp
> +    hsv.hue = 60 * ((r - g) / (max - min)) + 240;
黒の場合、0除算になりませんか？
正確に、RGB(0,0,0)となることは稀だろうけど

@Tamiyas より

2019-06-19 05:43 UTC, korosuke613 commented on src/module/api/core/Controller.cpp
> +  hsv.saturation = (max - min) / max * 100;
`max` が0のとき0除算になります

@Tamiyas より

2019-06-19 05:43 UTC, korosuke613 commented on test/dummy/Controller.h
> +  void convertHsv(std::uint16_t& r, std::uint16_t& g, std::uint16_t& b)
引数の型を変えたのはどうしてですか？
`int&` -> `std::uint16_t&`

@Tamiyas より

2019-06-19 08:36 UTC, sigenaga approved these changes

2019-06-22 05:04 UTC, sigenaga approved these changes

2019-06-22 15:47 UTC, korosuke613 approved these changes
![LGTM](https://lgtmoon.herokuapp.com/images/22429)

2019-06-22 15:48 UTC, merged