Fix: TurnControlクラスのメンバとしてPidを持つように変更
KatLab-MiyazakiUniv/etrobocon2019 pull request #111
Opened 2019-06-18 08:45 UTC by arimakaoru

### 変更点
- TurnControlクラスのメンバ変数にPidを追加
- TurnControlクラスのコンストラクタの引数にtargetBrightness, Kp, Ki, Kdを追加
- TurnControlクラスのcalculateTurnでメンバ変数のPidを使用するように変更
- LineTracerクラスにメンバ変数TurnControlの初期化処理を追加

### 実機テストの結果（実機テストが必要な場合）
 - 例: 10回走行させた平均値を書く
 - 例: 誤差率 [%] を書く
 - 例: 前回の手法との差を書く

#### 誤差率の計算式
誤差率 = （「測定値」 - 「理論値」） / 「理論値」 * 100

2019-06-18 14:39 UTC, Tatsumi0000 commented on src/module/TurnControl.cpp
>   */
これが何をするメソッドかコメントがあるとより分かりやすいかも．
[参考資料](https://github.com/arimakaoru/etrobocon2019/blob/ticket-96/src/module/Pid.cpp#L51)

2019-06-18 14:39 UTC, Tatsumi0000 commented on src/module/TurnControl.cpp
> + *  [TurnControl::turnControl]
[TurnControl::turnControl]でいいんだっけ？
[TurnControl::TurnControl]じゃない？
それか，***コンストラクタ***とでも書いとく？

2019-06-18 14:39 UTC, Tatsumi0000 commented on src/module/TurnControl.cpp
> +  : pid(static_cast<double>(targetBrightness), Kp, Ki, Kd)
[ヘッダファイル](https://github.com/arimakaoru/etrobocon2019/blob/ticket-96/src/module/TurnControl.h#L16)には，コンストラクタのkp,ki,kdにデフォルト引数0.0があるけどこっち（cppファイル）には，書かなくていいの？
それともヘッダファイルに書いとけばcppファイルの方も自動でヘッダファイルと同じ値（0.0）になるんだっけ？
あと，デフォルト引数のことをコメントに書いとくといいかも

2019-06-18 14:48 UTC, Tatsumi0000 commented on src/module/TurnControl.cpp
> + *  @param  Kd                [Dゲイン]
デフォルト引数のことをコメントに書いとくといいかも

2019-06-19 05:27 UTC, korosuke613 requested changes
ついでにTypo直しといて〜
それ以外は問題ないと思います。

2019-06-19 05:27 UTC, korosuke613 commented on src/module/LineTracer.cpp
> + *  @bfief 走行距離や目標スピード、スピード制御PID、回転制御PIDを NormalCourseProperty
Typo
bfief -> brief

2019-06-19 06:45 UTC, Tatsumi0000 commented
デフォルト引数は，ヘッダファイル，cppファイルどっちかで良かったらしいです🙄

2019-06-19 08:35 UTC, sigenaga approved these changes

2019-06-20 01:57 UTC, arimakaoru commented on src/module/TurnControl.cpp
>   */
コメントを追加しました。

2019-06-20 01:57 UTC, arimakaoru commented on src/module/TurnControl.cpp
> + *  [TurnControl::turnControl]
「コンストラクタ」に修正しました。

2019-06-20 02:01 UTC, arimakaoru commented on src/module/TurnControl.cpp
> + *  @param  Kd                [Dゲイン]
デフォルト値は削除しました。

2019-06-20 02:01 UTC, arimakaoru commented on src/module/LineTracer.cpp
> + *  @bfief 走行距離や目標スピード、スピード制御PID、回転制御PIDを NormalCourseProperty
修正しました。

2019-06-20 05:24 UTC, korosuke613 approved these changes
ガッチャ！

2019-06-20 11:14 UTC, Tatsumi0000 approved these changes
[![LGTM](https://lgtm.in/p/Ae6XWWZdq)](https://lgtm.in/i/Ae6XWWZdq)

2019-06-20 11:18 UTC, merged