closed #109 Distanceクラスのテストコードを修正
KatLab-MiyazakiUniv/etrobocon2019 pull request #113
Opened 2019-06-18 08:50 UTC by Oiwane

### 変更点
DistanceTest.cppの修正
Distanceクラスで使用するヘッダをインクルードする場所を変更
Distanceクラスで宣言したメソッドの説明コメントの場所を変更

### 実機テストの結果（実機テストが必要な場合）
なし

2019-06-19 05:50 UTC, korosuke613 requested changes
CIが動いていないor報告が届いていないので、CircleCIにて、ReBuildを行ってください...

2019-06-19 06:26 UTC, Oiwane commented
@korosuke613 
ReBuildをしました
確認よろしくお願いします

2019-06-19 06:28 UTC, korosuke613 approved these changes
inじゃねーの！？

2019-06-19 08:33 UTC, sigenaga requested changes

2019-06-19 08:33 UTC, sigenaga commented on test/DistanceTest.cpp
> +    Controller controller;
片一方の最初が大文字で、もう一方の最初の文字が小文字ですけど大丈夫ですか？

2019-06-19 08:44 UTC, Oiwane commented on test/DistanceTest.cpp
> +    Controller controller;
大丈夫だよ
これは変数の宣言みたいなものだから

2019-06-19 08:46 UTC, sigenaga approved these changes
おっけーです

2019-06-19 08:46 UTC, sigenaga commented on test/DistanceTest.cpp
> +    Controller controller;
分かりました。ありがとうございます

2019-06-20 02:12 UTC, arimakaoru approved these changes

2019-06-20 11:20 UTC, merged