closed #102 speedcontrolクラスにprevDistanceの更新処理を追加する
KatLab-MiyazakiUniv/etrobocon2019 pull request #115
Opened 2019-06-18 09:33 UTC by match97

### 変更点
speedcontrolクラスにprevDistanceの更新処理を入れた

2019-06-19 05:48 UTC, korosuke613 requested changes
`Controller`クラスが持つ、`Motor`クラスのインスタンスは、`private`になったので、
`Motor::getCount()`は外部のクラスから使用できないよ

元々の、`Controller::getLeftMotorCount()`と`Controller:: getRightMotorCount()`を使えばいいので、直してね

2019-06-19 05:48 UTC, korosuke613 commented on test/SpeedControlTest.cpp
> -    int leftAngle = controller.getLeftMotorCount();
このままでいいよ

2019-06-19 05:48 UTC, korosuke613 commented on test/SpeedControlTest.cpp
> -    int rightAngle = controller.getRightMotorCount();
このままでいいよ

2019-06-19 05:48 UTC, korosuke613 commented on test/SpeedControlTest.cpp
> -    leftAngle = controller.getLeftMotorCount();
このままでいいよ

2019-06-19 05:48 UTC, korosuke613 commented on test/SpeedControlTest.cpp
> -    rightAngle = controller.getRightMotorCount();
このままでいいよ

2019-06-19 08:27 UTC, sigenaga approved these changes
異常なし！

2019-06-20 02:24 UTC, arimakaoru commented on test/SpeedControlTest.cpp
> +    // 4ms後の左右のモータの角位置を取得
この処理は4ms待つ前の処理なので、コメント間違っていませんか？

2019-06-20 02:24 UTC, arimakaoru commented on test/SpeedControlTest.cpp
> +    prevDistance = dist.getDistance(leftAngle, rightAngle);
`prevDistance = nextDistance;`でもいいのでは・・・？

2019-06-20 02:24 UTC, arimakaoru commented on src/module/SpeedControl.cpp
> +  prevDistance = dist.getDistance(leftAngle, rightAngle);
`prevDistance = nextDistance;`でもいいのでは・・・？

2019-06-20 15:17 UTC, Tatsumi0000 commented on src/module/SpeedControl.cpp
>  SpeedControl::SpeedControl(Controller& controller_, int targetSpeed, double Kp, double Ki,
ここに，コメントがあると嬉しいな．
[参考資料](https://github.com/KatLab-MiyazakiUniv/etrobocon2019/blob/master/src/module/TurnControl.cpp#L8-L18)

2019-06-20 15:19 UTC, Tatsumi0000 commented on src/module/SpeedControl.cpp
> +  : controller(controller_), dist(), pid(targetSpeed, Kp, Ki, Kd)
ここに，コメントがあると嬉しいな．
[参考資料](https://github.com/KatLab-MiyazakiUniv/etrobocon2019/blob/master/src/module/TurnControl.cpp#L8-L18)

2019-06-21 05:24 UTC, korosuke613 approved these changes
![LGTM](https://lgtmoon.herokuapp.com/images/22349)

2019-06-21 05:25 UTC, merged