closed #87  LineTracerクラスでSpeedControlクラスを利用できるようにする
KatLab-MiyazakiUniv/etrobocon2019 pull request #123
Opened 2019-06-23 22:05 UTC by korosuke613

### 変更点
- SpeedControlを組込
- devcontainer内でテストをデバッグできるようにした

2019-06-23 22:18 UTC, Tamiyas requested changes
このコードがもっと良くなるように、いくつか指摘しました！

2019-06-23 22:18 UTC, Tamiyas commented on src/module/LineTracer.h
>      Controller controller;
Controllerの初期化をしてください、あと型を参照型にして！
EtRobocon2019で生成したControllerのオブジェクトをそのまま参照で受け継ぐみたいな感じで

2019-06-23 22:18 UTC, Tamiyas commented on src/module/SpeedControl.cpp
> +  double currentSpeed = nextDistance - prevDistance;
ここの変更箇所をプルリクに詳しく書いて

2019-06-23 22:18 UTC, Tamiyas commented on src/module/LineTracer.h
>  struct PidParameter
`PidParameter` は、Pid.h にある `PidGain` 構造体と内容がカブっているので
`PidGain` に統一してください

2019-06-24 06:25 UTC, korosuke613 commented on src/module/LineTracer.h
>      Controller controller;
[fix](https://github.com/KatLab-MiyazakiUniv/etrobocon2019/pull/123/commits/8eef19842ba563a86c2671439a4cda5292fccf7e)

2019-06-24 06:25 UTC, korosuke613 commented on src/module/LineTracer.h
>  struct PidParameter
[fix](https://github.com/KatLab-MiyazakiUniv/etrobocon2019/pull/123/commits/ee5816dcbf537e8c23d1a58abff0a7572dec8195)

2019-06-24 06:28 UTC, korosuke613 commented on src/module/SpeedControl.cpp
> +  double currentSpeed = nextDistance - prevDistance;
fix

2019-06-24 07:39 UTC, Tamiyas commented on src/module/SpeedControl.cpp
> +  double currentSpeed = nextDistance - prevDistance;
この改善は、理論を崩すように思えたけど（だって速度じゃないし...）
微分時間さえも `D` ゲインに含めたと考えると理解できるものかもしれない

実際、PID制御理論の一部では
`Kd = Kp * Td` と定義しているらしい（`Td` は微分時間）

2019-06-24 07:40 UTC, Tamiyas approved these changes
LGTM

2019-06-24 08:27 UTC, korosuke613 commented on src/module/SpeedControl.cpp
> +  double currentSpeed = nextDistance - prevDistance;
なるほどね
たしかに考察の余地はあるわ

2019-06-24 08:57 UTC, Oiwane approved these changes

2019-06-24 09:00 UTC, merged