closed #75 速度を指定して直進・後進できる関数を追加
KatLab-MiyazakiUniv/etrobocon2019 pull request #126
Opened 2019-06-24 12:28 UTC by Oiwane

### 変更点
moveBySpeedとmoveByPidAndSpeed、setPwmValueを追加
※良い関数名がある方は教えてください

### 実機テストの結果（実機テストが必要な場合）
 - 速度を指定して直進・後進できました

2019-06-24 14:36 UTC, korosuke613 requested changes
コメントが残ってるんだよなぁ

2019-06-24 14:36 UTC, korosuke613 commented on src/module/Navigator.cpp
> +      double pwm = speedControl.calculateSpeed(specifiedSpeed, 0.60, 0.05, 0.04);
[提案]Kp, Ki, Kdはハードコードするんじゃなくて、setterかなんかで決められるようにしてもいいかもね

2019-06-24 14:36 UTC, korosuke613 commented on src/module/Navigator.h
> +  // void forward(double specifiedDistance, double goalDistance, int pwm, double alpha = 0.0);
コメントが残ってるんだよなぁ

2019-06-24 14:36 UTC, korosuke613 commented on src/module/Navigator.h
> +  // void backward(double specifiedDistance, double goalDistance, int pwm, double alpha = 0.0);
コメントが残ってるんだよなぁ

2019-06-24 17:23 UTC, Tamiyas requested changes
いくつか、指摘しました。
関数名については良い案が出せなくて、ごめん 😭

2019-06-24 17:23 UTC, Tamiyas commented on src/module/Navigator.cpp
>    controller.setRightMotorPwm(0);
今回のチケット対象ではないけど、この部分の処理は
`controller` の `stopMotor` 関数を使った方が簡潔でわかりやすい気がします

2019-06-24 17:23 UTC, Tamiyas commented on src/module/Navigator.cpp
> +      setPwmValue(-std::abs(static_cast<int>(pwm)));
`std::abs` の引数の型は、`float` または `double` ですね（https://cpprefjp.github.io/reference/cmath/abs.html）
`setPwmValue(static_cast<int>(-std::abs(pwm)))` の間違いですか？

2019-06-24 17:23 UTC, Tamiyas commented on src/module/Navigator.cpp
> +Navigator::Navigator(Controller& controller_, SpeedControl& speedControl_) : distance(), controller(controller_), speedControl(speedControl_) {}
`SpeedControl` は、別に `Navigator` が作ってもいい気がするけどなあ。
何か理由があるんですか？

2019-06-24 17:23 UTC, Tamiyas commented on src/module/Navigator.cpp
> +void Navigator::moveBySpeed(double specifiedDistance, int specifiedSpeed)
`by` なのかなあ `at` な気がする
まあ、`moveAtSpeed` としても意味は人に伝わらないか
例えば、move at specified speed （指定速度で移動する）ならわかるけど関数名としては長い？

2019-06-24 17:23 UTC, Tamiyas commented on src/module/Navigator.cpp
> +void Navigator::moveByPidAndSpeed(double specifiedDistance, int specifiedSpeed, const double pGain, const double iGain,
わーお！ すごい関数名 😨 
やっぱり、by の後ろに来るのは手段とか方法の気がするんですよね～
完全に書くなら move at specified speed by PID controlなんだろうけど、長すぎるよね

2019-06-25 00:25 UTC, sigenaga approved these changes

2019-06-25 03:17 UTC, Oiwane commented on src/module/Navigator.h
> +  // void forward(double specifiedDistance, double goalDistance, int pwm, double alpha = 0.0);
コメント、削除しました

2019-06-25 03:17 UTC, Oiwane commented on src/module/Navigator.h
> +  // void backward(double specifiedDistance, double goalDistance, int pwm, double alpha = 0.0);
コメント、削除しました

2019-06-25 03:19 UTC, Oiwane commented on src/module/Navigator.cpp
> +Navigator::Navigator(Controller& controller_, SpeedControl& speedControl_) : distance(), controller(controller_), speedControl(speedControl_) {}
これといった理由はないです。
変更したほうがいいですかね？

2019-06-25 03:40 UTC, Tamiyas commented on src/module/Navigator.cpp
> +Navigator::Navigator(Controller& controller_, SpeedControl& speedControl_) : distance(), controller(controller_), speedControl(speedControl_) {}
変更した方がいいと思います。
速度を指定しないでNavigatorを使うこともある、ということを考えると
SpeedControlをNavigatorが作成する方が使い勝手がいいと思います。

2019-06-25 03:41 UTC, Oiwane commented on src/module/Navigator.cpp
> +void Navigator::moveBySpeed(double specifiedDistance, int specifiedSpeed)
個人的には4語程度ならいいかなと思っています。
ということでそちらに変更します。

2019-06-25 03:43 UTC, Oiwane commented on src/module/Navigator.cpp
> +Navigator::Navigator(Controller& controller_, SpeedControl& speedControl_) : distance(), controller(controller_), speedControl(speedControl_) {}
> 速度を指定しないでNavigatorを使うこともある、ということを考えると

ということは『Navigatorで作成＝メソッド内で宣言する』ということでいいのでしょうか

2019-06-25 03:45 UTC, Tamiyas commented on src/module/Navigator.cpp
> +Navigator::Navigator(Controller& controller_, SpeedControl& speedControl_) : distance(), controller(controller_), speedControl(speedControl_) {}
うん、そうだね。

2019-06-25 03:58 UTC, Oiwane commented on src/module/Navigator.cpp
> +void Navigator::moveByPidAndSpeed(double specifiedDistance, int specifiedSpeed, const double pGain, const double iGain,
ほかにいい案が出ないのでとりあえず現在の名前よりも意味が通っている`moveAtSpecifiedSpeedByPid`にしておきます。

2019-06-25 04:22 UTC, Oiwane commented on src/module/Navigator.cpp
> +      double pwm = speedControl.calculateSpeed(specifiedSpeed, 0.60, 0.05, 0.04);
そのように修正しました。

2019-06-25 04:22 UTC, Oiwane commented on src/module/Navigator.cpp
>    controller.setRightMotorPwm(0);
変更しました。

2019-06-25 04:22 UTC, Oiwane commented on src/module/Navigator.cpp
> +      setPwmValue(-std::abs(static_cast<int>(pwm)));
間違えていました。
修正しました。

2019-06-25 04:23 UTC, Oiwane commented on src/module/Navigator.cpp
> +Navigator::Navigator(Controller& controller_, SpeedControl& speedControl_) : distance(), controller(controller_), speedControl(speedControl_) {}
そのように変更しました。

2019-06-25 04:31 UTC, Tamiyas commented on src/module/Navigator.h
> +  double KpForSpeed;
`PidGain` 構造体を使った方が意味が伝わりやすく、変数をまとめられると思います

2019-06-25 04:38 UTC, Oiwane commented on src/module/Navigator.h
> +  double KpForSpeed;
変更しました。
これでいいでしょうか。

2019-06-25 05:26 UTC, korosuke613 commented
![LGTM](https://lgtmoon.herokuapp.com/images/22696)

2019-06-25 05:26 UTC, korosuke613 approved these changes
![LGTM](https://lgtmoon.herokuapp.com/images/22696)

2019-06-25 05:27 UTC, Tamiyas approved these changes
よいと思います
早めの修正ありがとうございます！

2019-06-25 05:27 UTC, merged