closed #137 オドメトリ手法を用いて走行体の回転角度を取得する
KatLab-MiyazakiUniv/etrobocon2019 pull request #148
Opened 2019-06-30 07:26 UTC by Tamiyas

### 変更点
- 走行体が自転したときの回転角度（yawing）を求めるRotationクラスを作成した
- 走行体の走行距離と回転角度を求める式をドキュメントにまとめた

### 実機テストの結果（実機テストが必要な場合）
走行体を90度回転させて、実機テストをした。
トレッド幅は実測で141mmだが、141mmで回転角度を求めると誤差が大きい。そこで、トレッド幅を130mmにしたところ、高い精度を得られた。

https://photos.app.goo.gl/nznx6UcE1RRKCni67

2019-07-01 10:06 UTC, sigenaga approved these changes

2019-07-01 10:18 UTC, korosuke613 requested changes
正直他は大丈夫だと思う

2019-07-01 10:18 UTC, korosuke613 commented on src/module/Rotation.h
> +  const double Tread;   // 走行体のトレッド幅（両輪の間の距離） [mm]
constだから先頭大文字？

2019-07-01 10:23 UTC, Tamiyas commented on src/module/Rotation.h
> +  const double Tread;   // 走行体のトレッド幅（両輪の間の距離） [mm]
そうです。PidGainの構造体のメンバーをKp、Ki、Kdとしたように大文字にしました。
しかし、Distanceクラスは定数が小文字なので、修正した方がよければ直します。

2019-07-02 07:17 UTC, korosuke613 approved these changes
![LGTM](https://lgtmoon.herokuapp.com/images/13161)

2019-07-02 07:18 UTC, merged