closed #138 controllerクラスにジャイロセンサーを取得する関数の追加
KatLab-MiyazakiUniv/etrobocon2019 pull request #154
Opened 2019-07-03 12:01 UTC by match97

### 変更点
controllerクラスにジャイロセンサーを取得する関数の追加
取得した角度の範囲は[0-360]とした
### 実機テストの結果（実機テストが必要な場合）
各テストは10回行った。
-反時計回りに90度回す  ->[86-93]の範囲,平均:89.9度
-反時計回りに180度回す->[175-186]の範囲,平均:179.2度
-反時計回りに270度回す->[265-276]の範囲,平均:269.9度
-反時計回りに360度回す->[351-4]の範囲,平均:356.7度

-時計回りに90度回す->[269-274]の範囲,平均:272.0度
-時計回りに180度回す->[176-186]の範囲,平均:182.0度
-時計回りに270度回す->[85-97]の範囲,平均:91.0度
-時計回りに360度回す->[350-6]の範囲,平均:1.8度

#すべて手作業でのテストであったため精度は良くない
[angleTest.xlsx](https://github.com/KatLab-MiyazakiUniv/etrobocon2019/files/3354848/angleTest.xlsx)

2019-07-04 03:49 UTC, sigenaga approved these changes

2019-07-04 10:56 UTC, Tamiyas requested changes
気になる箇所を4点指摘させていただきました。

2019-07-04 10:56 UTC, Tamiyas commented on src/module/api/core/Controller.cpp
> +int Controller::getAngleOfRotation()
右手系（反時計回りを正）であることを明記すると分かりやすいですね。

ちなみに、範囲を0から360度としたのは何故ですか？
負の角度を導入した方が、時計回りの旋回（例えば右折）命令を出すときに処理が複雑にならない気がします。

2019-07-04 10:56 UTC, Tamiyas commented on src/module/api/core/Controller.h
> +  int getAngle();
`getAngle()`
`getAnglerVelocity()`
`reset()`
`setOffset()`
の実装はどこにありますか？

2019-07-04 10:56 UTC, Tamiyas commented on src/module/api/core/Controller.h
> +  int getAnglerVelocity();
`getAnglerVelocity()` は間違っていますね。角速度は英語で、 `angular velocity` です。

EV3APIと名前を合わせるのならば、別に構いませんが。

2019-07-04 10:56 UTC, Tamiyas commented on test/dummy/Controller.h
> +    int angle = 0;
`angle` の更新処理はどこに書いていますか？

2019-07-05 08:51 UTC, korosuke613 requested changes
submodule`etrobocon2019`を消してください

2019-07-05 08:51 UTC, korosuke613 commented on test/dummy/Controller.h
> +    int angle = 0;
publicだから、テスト時に書き換えるんじゃね？

2019-07-06 08:24 UTC, sigenaga approved these changes

2019-07-08 08:50 UTC, korosuke613 approved these changes
![LGTM](https://lgtmoon.herokuapp.com/images/23624)

2019-07-08 09:08 UTC, Tamiyas approved these changes
LGTM

2019-07-08 09:10 UTC, merged