規約の簡略化をしました
KatLab-MiyazakiUniv/etrobocon2019 pull request #162
Opened 2019-07-09 07:31 UTC by harakai

主に「～節を参照のこと」の部分に参照先の内容を書いて見やすくしました。

2019-07-09 07:45 UTC, korosuke613 requested changes
- 協議規約を競技規約に変えてほしい。ファイル名とタイトル
- Wordファイルも入れて

2019-07-09 07:57 UTC, harakai commented
> * 協議規約を競技規約に変えてほしい。ファイル名とタイトル
> * Wordファイルも入れて

協議→競技にしました。
Wordファイルを追加しました。

2019-07-11 07:46 UTC, korosuke613 approved these changes
![LGTM](https://lgtmoon.herokuapp.com/images/23914)

2019-07-11 07:48 UTC, Tatsumi0000 approved these changes
お疲れサマンサタバサ．

![LGTM](https://lgtmoon.herokuapp.com/images/14899)

2019-07-11 07:48 UTC, merged