closed #168 旋回値制御にローパスフィルター制御を加える
KatLab-MiyazakiUniv/etrobocon2019 pull request #170
Opened 2019-07-16 03:39 UTC by arimakaoru

### 変更点
- TurnControl::calculateTurnでFilter::lowPassFilterを使用するようにした
- lowPassFilterには現在の光センサーの値を渡すようにした
- lowPassFilterの前回の値を参考にする割合は0.9にした

###  実機テスト
1つ目の動画はフィルターなし
2つ目の動画はフィルターあり
https://photos.google.com/share/AF1QipPxBD_rJFd5rVuRP_V1MYh9onPGBVAt62SQPHfVtmhVeFSu7eBb7hxhQIlz7gVNCg?key=T21YcUZDWGNmcjNpZElQbTBNdW9US1h4VzhrNk9B

2019-07-16 04:38 UTC, sigenaga approved these changes
異常なしであります(｀･ω･´)

2019-07-19 08:14 UTC, sigenaga approved these changes
異常なしでありますヽ(`Д´)ﾉ

2019-07-19 08:17 UTC, sigenaga requested changes

2019-07-19 08:17 UTC, sigenaga commented on src/module/TurnControl.cpp
>  TurnControl::TurnControl(int targetBrightness, double Kp, double Ki, double Kd)
TurnControlではなく、turnControlではないでしょうか。

2019-07-22 08:05 UTC, Tamiyas reviewed
遅れてすみません。
気になるところを少し書きましたが、実行に影響しない部分なので
Request changes ではなく Comment としています。

2019-07-22 08:05 UTC, Tamiyas commented on src/module/TurnControl.cpp
>  TurnControl::TurnControl(int targetBrightness, double Kp, double Ki, double Kd)
いや、これは `TurnControl` で正しいよ
コンストラクタは、クラス名::クラス名で定義するから

2019-07-22 08:05 UTC, Tamiyas commented on test/TurnControlTest.cpp
> +    int foward = 100;
foward ではなく forward ですかね

2019-07-22 08:05 UTC, Tamiyas commented on test/TurnControlTest.cpp
> +    int foward = 50;
foward ではなく forward ですかね

2019-07-23 01:18 UTC, arimakaoru commented on test/TurnControlTest.cpp
> +    int foward = 100;
レビューありがとうございます。
修正しました。

2019-07-23 01:18 UTC, arimakaoru commented on test/TurnControlTest.cpp
> +    int foward = 50;
修正しました。

2019-07-23 01:25 UTC, Tamiyas approved these changes
OKです！

2019-07-23 04:42 UTC, sigenaga commented on src/module/TurnControl.cpp
>  TurnControl::TurnControl(int targetBrightness, double Kp, double Ki, double Kd)
了解です(''◇'')ゞ

2019-07-23 04:42 UTC, sigenaga approved these changes

2019-07-23 05:16 UTC, merged