closed #163 光センサーの値を学習して色識別する学習器を作る
KatLab-MiyazakiUniv/etrobocon2019 pull request #174
Opened 2019-07-22 15:24 UTC by Tamiyas

### 変更点
 - Controllerの色識別処理の精度をAIを用いて向上させました。

機械学習手法は決定木です。300個のデータで学習させ、90個の未知データでテストしました。
テスト結果は **正答率100%** です。

処理プログラムがものすごく汚いですが、以下の決定木を忠実にプログラムに書き起こしただけなので
許してください。

![tree_visualization](https://user-images.githubusercontent.com/39326935/61643932-c89d9b00-acde-11e9-80e0-dd39dfa8488a.png)

機械学習のコードは後日、僕のリポジトリにあげる予定です。
とりあえず色識別処理だけupしておきます。

2019-07-23 06:00 UTC, korosuke613 requested changes
これってControllerクラスに入ってるから、テストができないのが残念だねぇ
これらの処理を別クラスに分けるべきだと思う？

特に文句はないけど、コメントを見てね

2019-07-23 06:00 UTC, korosuke613 commented on src/module/api/core/Controller.cpp
> +          if(status.hue <= 40.8904){
これらの数字ってマジックナンバーになってるけど大丈夫？

2019-07-23 06:04 UTC, Tamiyas commented on src/module/api/core/Controller.cpp
> +          if(status.hue <= 40.8904){
確かにマジックナンバーではあるだろうけど、
定数にしたところで保守性が上がるとも思えない

これは、このままでOKとはならないかな？

2019-07-23 06:06 UTC, Tamiyas commented
テストできないのは問題かもね
一応、今回の関数を別環境で作ってテストはしています

テスト内容はプルリク通り、90この未知データを使いました

2019-07-23 06:23 UTC, sigenaga requested changes

2019-07-23 06:23 UTC, sigenaga commented on src/module/api/core/Controller.cpp
> +            return Color::black;
このif文の間にコメントがあった方が分かりやすいと思います

2019-07-23 08:45 UTC, Oiwane approved these changes
指摘されていないところ以外で気になったところは特にありませんでした。

2019-07-23 09:30 UTC, korosuke613 commented on src/module/api/core/Controller.cpp
> +          if(status.hue <= 40.8904){
そういうことなら、Inじゃねーの！？

2019-07-23 09:33 UTC, korosuke613 approved these changes
まま、今回はエアロ
![LGTM](https://lgtmoon.herokuapp.com/images/13976)

2019-07-26 02:23 UTC, arimakaoru approved these changes

2019-07-26 02:54 UTC, sigenaga approved these changes
異常なしであります(｀･ω･´)

2019-07-26 02:54 UTC, sigenaga commented on src/module/api/core/Controller.cpp
> +            return Color::black;
関係なかったです

2019-07-29 02:23 UTC, merged

2019-07-29 02:23 UTC, Tamiyas commented
ZenHubがうるさいのでマージしました