closed #167 docsディレクトリ内にレビューのチェックリストの作成
KatLab-MiyazakiUniv/etrobocon2019 pull request #175
Opened 2019-07-23 04:39 UTC by match97

**変更点**
docsディレクトリ内にレビューのチェックリストを作成した
レビューのチェックリストにはコーディング規約の内容も含んでいる

2019-07-23 04:43 UTC, sigenaga approved these changes
異常なしであります(｀･ω･´)

2019-07-23 09:35 UTC, korosuke613 requested changes
While文やfor文の中で、`contrloller.tslpTsk(4)`が入ってるかの確認も加えてください

2019-07-24 05:42 UTC, harakai reviewed
いいと思います。
レビュー初心者なので大変助かります。

2019-07-24 16:35 UTC, match97 commented
> While文やfor文の中で、`contrloller.tslpTsk(4)`が入ってるかの確認も加えてください

変更を付け加えました。

2019-07-26 02:21 UTC, arimakaoru approved these changes

2019-07-26 02:49 UTC, Tamiyas reviewed
「コメントする時」というのは、「レビューする時」ということですよね！？
プログラム中のコメントと混同してしまう気がします。

また、今回のチケットでは、レビューする際にチェックする項目をドキュメント化すると思っていたんですが
「できれば改善点を提案する」であったり、「補足を入れる」であったりと
レビューした後の内容だけが記述されているように思います。レビュー時のチェック項目はドキュメント化しないのでしょうか。

僕の勘違いだったら申し訳ないので、Commentとしておきます...

2019-07-27 02:30 UTC, match97 commented
> 「コメントする時」というのは、「レビューする時」ということですよね！？
> プログラム中のコメントと混同してしまう気がします。
> 
> また、今回のチケットでは、レビューする際にチェックする項目をドキュメント化すると思っていたんですが
> 「できれば改善点を提案する」であったり、「補足を入れる」であったりと
> レビューした後の内容だけが記述されているように思います。レビュー時のチェック項目はドキュメント化しないのでしょうか。
> 
> 僕の勘違いだったら申し訳ないので、Commentとしておきます...

「コメントするとき」->「レビューするとき」に変更しました。

今回のチケットの完了条件が「docsディレクトリ内にレビューのチェックリストを作成している」と「レビューのチェックリストにはコーディング規約の内容も含んでいる」であったため、ドキュメント化ではなくdocs内にチェックリストを移動させ、数人に合った方がいいものを聞き取りしそれを新しく追加するものである、とこちら側は考えておりました。

2019-07-29 02:25 UTC, Tamiyas commented
> > 「コメントする時」というのは、「レビューする時」ということですよね！？
> > プログラム中のコメントと混同してしまう気がします。
> > また、今回のチケットでは、レビューする際にチェックする項目をドキュメント化すると思っていたんですが
> > 「できれば改善点を提案する」であったり、「補足を入れる」であったりと
> > レビューした後の内容だけが記述されているように思います。レビュー時のチェック項目はドキュメント化しないのでしょうか。
> > 僕の勘違いだったら申し訳ないので、Commentとしておきます...
> 
> 「コメントするとき」->「レビューするとき」に変更しました。
> 
> 今回のチケットの完了条件が「docsディレクトリ内にレビューのチェックリストを作成している」と「レビューのチェックリストにはコーディング規約の内容も含んでいる」であったため、ドキュメント化ではなくdocs内にチェックリストを移動させ、数人に合った方がいいものを聞き取りしそれを新しく追加するものである、とこちら側は考えておりました。

そうなんですね。みんなの「あった方がいいもの」をまとめたのであれば、何も文句はありません :smile:

2019-07-29 02:25 UTC, Tamiyas approved these changes

2019-07-29 08:42 UTC, korosuke613 approved these changes
![LGTM](https://lgtmoon.herokuapp.com/images/8980)

2019-07-29 08:42 UTC, merged