closed #169 スタート位置で自己位置調整する
KatLab-MiyazakiUniv/etrobocon2019 pull request #184
Opened 2019-07-24 04:47 UTC by arimakaoru

## 目的
キャリブレーションでの属人化をできる限り減らすこと。
具体的には以下の3点を誰がキャリブレーションを行っても、ほとんど同じ状態にする。
- スタートラインから走行体までの距離
- 光センサーの位置（白黒のちょうど中間地点が望ましい）
- スタートラインに対しての走行体の角度（垂直が望ましい）

## 変更点
キャリブレーション中にスタート位置の自己位置調整を行うようにしました。
変更後のキャリブレーション手順は以下になります。

1. カメラシステムの有無を選択する（On/Off）
2. コースを選ぶ（Left/Right）
3. 白の明るさを取得する
4. 黒の明るさを取得する
5. スタートラインとは逆向きに走行体を置く（Lコースなら左エッジ、Rコースなら右エッジ）
6. 走行体の左ボタンを押す

走行体は[動画](https://photos.app.goo.gl/w2dNchNSdsPindmr9)のように動きます。

## 実機テストの結果（実機テストが必要な場合）
|スタートラインから右タイヤの中央までの距離(cm)|targetBrightness - currentBrightness|スタートラインに対して走行体は垂直か（目視）|
|----------|----------|----------|
|14.2|-5|o|
|14.1|-3|o|
|16.0|0|o|
|14.1|-5|x|
|14.4|5|o|
|15.0|5|x|
|15.6|-5|o|
|14.1|5|x|
|14.0|5|o|
|16.5|4|x|

- スタートラインから走行体までの距離はブレが大きい
- 光センサーの値は目標値±5以内になるようにしているため、達成率は100%である
- 下の写真のようにスタートラインに対して走行体がかなり傾く場合がある
https://photos.google.com/photo/AF1QipPFRdBe1krSZDAjacsLJjM0tbDsSOofofD7Vknp
https://photos.google.com/photo/AF1QipNte-7uyCCb3DEBAoBakMtSrMRnk3eVbKKTLWcL

## 今後のこと
### 精度を上げる
- ライントレースが高精度にできれば上手くいくかもしれない
- スタートラインに対して走行体を垂直にする実装方法がわからない

### 別の方法でキャリブレーションでの属人化を減らす
目的に対応するキャリブレーションでのチェックポイントを作成し、全員で徹底する。
チェックポイントの例

- 走行体のアームがスタートラインギリギリにある
- 光センサーの値が(白+黒)/2の位置である
    - targetBrightnessとcurrentBrightnessの値をリアルタイムでディスプレイ上に表示する機能を作る
- スタートラインに対して走行体は垂直である
    - キャリブレーションで道具（三角定規などの垂直を測れそうなもの）を使っても良いなら使う

2019-07-24 05:35 UTC, korosuke613 requested changes
やり方は良いと思うが、現在のライントレースの精度ではうまく行かないので、実用的では無いと思います。

しかし、今後、ライントレース精度が上がった場合に、利用できる可能性があるため、関数自体は残しておいても良いと思います。

したがって、`Calibrator::caribration()`において、`setupPosition()`を実行しないようにすることを要求します。

2019-07-24 05:35 UTC, korosuke613 commented on src/module/Calibrator.cpp
> +  if(!setupPosition()) {
今回は、うまく行っていないので、このif文はコメントアウトして、自己位置調整しないようにしよう

2019-07-24 05:35 UTC, korosuke613 commented on src/module/Calibrator.cpp
> +{
今後、ラインとレースの精度が上がった場合に利用できるので、このコードは残しておこう

2019-07-24 05:35 UTC, korosuke613 commented on test/CalibratorTest.cpp
> +  // TEST(Calibrator, calibrationTest)
もし`setupPosition()`を`Caribrator::calibration()`で使わない場合は、ここのコメントアウトを外して、テストしよう

2019-07-24 05:41 UTC, Tatsumi0000 reviewed
プログラム的には，特に問題は何もないと思います．
しかし，人手には勝てないっぽいので`master`にマージするのは
やめといたほうがいいかもしれませんね．

ので，`Comment`にしときます．

2019-07-24 05:41 UTC, Tatsumi0000 commented on src/module/Calibrator.cpp
> +  }
```cpp
if(!setupPosition()) return false;
```
短く書こうと思うとこうも書ける．

2019-07-24 16:13 UTC, match97 reviewed
先輩方の言う通り、今後のライントレースの向上を期待して関数自体は残し、実行しないようにするのが良いと自分も思います。

2019-07-25 05:09 UTC, sigenaga approved these changes
異常なしであります(｀･ω･´)

2019-07-26 02:14 UTC, arimakaoru commented on src/module/Calibrator.cpp
> +  if(!setupPosition()) {
修正しました。

2019-07-26 02:14 UTC, arimakaoru commented on src/module/Calibrator.cpp
> +{
修正しました。

2019-07-26 02:15 UTC, arimakaoru commented on test/CalibratorTest.cpp
> +  // TEST(Calibrator, calibrationTest)
修正しました。

2019-07-26 02:15 UTC, arimakaoru commented on src/module/Calibrator.cpp
> +  }
修正しました。

2019-07-26 07:38 UTC, Tatsumi0000 approved these changes
いいと思うンゴ．
![LGTM](https://lgtmoon.herokuapp.com/images/7100)

2019-07-29 08:43 UTC, korosuke613 approved these changes
![LGTM](https://lgtmoon.herokuapp.com/images/19684)

2019-07-31 00:34 UTC, closed without merging