closed #185 パソコンから受け取ったリストの通りに処理を実行する関数を作成
KatLab-MiyazakiUniv/etrobocon2019 pull request #186
Opened 2019-08-06 04:47 UTC by Oiwane

### 変更点

- BlockBingoクラスにexecOrder関数を作成
- それに伴い、列挙型Orderと構造体OrderPropertyを作成
- テストコードの追加

### 実機テストの結果（実機テストが必要な場合）

- こちらが指示したとおりに動きました

2019-08-06 08:54 UTC, sigenaga approved these changes
異常なしであります(｀・ω・´)

2019-08-07 03:30 UTC, Tatsumi0000 requested changes
レビューしました．
チェックをよろしくおねがいします！！

2019-08-07 03:30 UTC, Tatsumi0000 commented on src/module/BlockBingo.h
> +    for(OrderProperty property : propertys) {
```cpp
for(OrderProperty property : propertys) {
（if文省略）
}
```
これ（値渡し）だとコピーコストが大きいので．
```cpp
for(const auto& property : propertys) {
（if文省略）
}
```
こっち（const 参照渡し）の方がいいと思います．
後，右辺の型は決まっているので `auto`でいいと思います．

---
## 参考資料類
[C++高速化 ](https://heavywatal.github.io/cxx/speed.html)

2019-08-07 03:30 UTC, Tatsumi0000 commented on src/module/BlockBingo.h
> +      } else if(property.orderName == Order::COLOR) {
`Order`のenumの並びが，
```cpp
enum class Order { MOVE, SPIN, COLOR };
```
なので，この順番にif文の処理を書いたほうが美しいと思いますた．

2019-08-07 03:30 UTC, Tatsumi0000 commented on src/module/BlockBingo.h
> +        controller.speakerPlayToneFS6(100);
ここは，`for文`を抜けても動作を停止しないけど大丈夫ですか？
この後の駐車する処理とのつなぎをどうするべきか一緒に話し合いましょう．

2019-08-08 05:49 UTC, Oiwane commented on src/module/BlockBingo.h
> +    for(OrderProperty property : propertys) {
const 参照渡しに変更しました

2019-08-08 05:49 UTC, Oiwane commented on src/module/BlockBingo.h
> +      } else if(property.orderName == Order::COLOR) {
順番を変更しました

2019-08-08 05:51 UTC, Oiwane commented on src/module/BlockBingo.h
> +        controller.speakerPlayToneFS6(100);
Navigatorクラスの`move`、`spin`、`moveToSpecifiedColor`はそれぞれ関数の終わりに`controller.stopMotor`を呼び出しているので一応は停止します

2019-08-08 07:13 UTC, Tatsumi0000 approved these changes
いいと思いますた．

![LGTM](https://lgtmoon.herokuapp.com/images/20717)

2019-08-09 02:10 UTC, korosuke613 requested changes
テストが気になる

2019-08-09 02:10 UTC, korosuke613 commented on src/module/BlockBingo.h
> +  void execOrder(std::array<OrderProperty, N>& propertys)
テンプレート使ってる〜
arrayだからサイズを決めとかなきゃいけないからか

2019-08-09 02:10 UTC, korosuke613 commented on test/BlockBingoTest.cpp
> +    std::array<OrderProperty, 1> propertys = { { Order::MOVE, 0.0, Color::black } };
複数個の命令が来たときのテストはしなくても大丈夫ですか？

2019-08-10 00:37 UTC, Oiwane commented on test/BlockBingoTest.cpp
> +    std::array<OrderProperty, 1> propertys = { { Order::MOVE, 0.0, Color::black } };
```cpp
    Controller controller;
    BlockBingo blockbingo(controller);

    constexpr int arraySize = 6;
    std::array<OrderProperty, arraySize> propertys = { { { Order::MOVE, 0.0, Color::yellow },
                                                         { Order::SPIN, 90.0, Color::white },
                                                         { Order::COLOR, 0.0, Color::black },
                                                         { Order::MOVE, 0.0, Color::blue },
                                                         { Order::SPIN, -135.0, Color::green },
                                                         { Order::SPIN, 45.0, Color::red } } };


    blockbingo.execOrder<arraySize>(propertys);
```

このようなコードでテストを行おうとしたのですが

```
Errors while running CTest
```

何故か無限ループになるので省いてました
これは命令が2つ以上になると発生します
実機テストでは特に問題はなさそうに見えたのですが発生原因が不明です

2019-08-10 05:56 UTC, korosuke613 commented on test/BlockBingoTest.cpp
> +    std::array<OrderProperty, 1> propertys = { { Order::MOVE, 0.0, Color::black } };
あ〜

たぶんControllerクラス特有のなにかやね

ならばしゃーないか

ソフトウェアテストで検証できない部分は実機テストで検証すれば良いしね

2019-08-10 05:56 UTC, korosuke613 approved these changes
![LGTM](https://lgtmoon.herokuapp.com/images/25697)

2019-08-13 03:54 UTC, merged