Colesd: #144 PCと走行体のデータのやり取り
KatLab-MiyazakiUniv/etrobocon2019 pull request #187
Opened 2019-08-13 03:53 UTC by Tatsumi0000

## 注意
このチケットは，カメラシステムと走行体のプログラム，2つで1つのチケットです．
[カメラシステムのプログラムはこちら](https://github.com/Tatsumi0000/CameraSystem/tree/ticket-144-camera)
## 変更点

### PC
- 走行体にデータを送るPythonプログラムを新規作成
- PCから送るデータは，0から9の整数を3秒毎に送信
- デバッグ用にシリアルポートを探す関数を作成
### 走行体
- Bluetooth通信専用のタスクを新規作成
- Bluetooth関連の処理をまとめたクラスを新規作成
- パソコンから受信したデータをディスプレイに表示

### 実機テストの結果（実機テストが必要な場合）
 - ディスプレイの6行目に受け取ったデータを表示した

#### 誤差率の計算式
- なっしんぐ

2019-08-15 04:15 UTC, korosuke613 requested changes
テストを通してください。
また、プルリクタイトルのClosedの綴りが間違っています

2019-08-15 04:15 UTC, korosuke613 commented on src/module/Bluetooth.h
> +#include "ev3api.h"
ev3apiをインクルードしているものをテストしているため、テストが通りません。
ControllerクラスのようにダミーのBluetoothクラスを作るか、もしくは、Bluetooth.hでev3api.hをインクルードする代わりに、Controller.hをインクルードしてください。

2019-08-15 12:07 UTC, korosuke613 approved these changes
![LGTM](https://lgtmoon.herokuapp.com/images/26302)

2019-08-15 12:08 UTC, Tatsumi0000 commented on src/module/Bluetooth.h
> +#include "ev3api.h"
テストを通るようにしました．

#### 解決方法
---
テストを通すためには，ただ単に，`ev3api.h`の代わりに`Controller.h`をインクルードするだけではテストは通りませんでした．
`Bluetooth.h`と`Bluetooth.cpp`をapiディレクトリに移動しないとダメでした．

2019-08-15 12:08 UTC, Tatsumi0000 commented on src/module/Bluetooth.h
> +#include "ev3api.h"
タイトルの`Colsed`を`Closed`にしました．

2019-08-15 12:09 UTC, korosuke613 commented
Cloesd: #144 PCと走行体のデータのやり取り

ゥーーーー！

2019-08-15 13:05 UTC, sigenaga approved these changes
特に異常なしであります(｀・ω・´)

2019-08-16 06:01 UTC, Tamiyas reviewed
`serialOpen` はあるのに、`serialClose` がないのが気になる
いっそ、Bluetoothクラスのメンバー変数としてFILEポインタを閉じ込めて
デストラクタで解放させるように変更した方が安全な気がする。

まぁ、シリアル通信はメインタスクが終了するまで動き続けるから
些細な話かもしれないけど

2019-08-16 06:19 UTC, korosuke613 commented
Clo**es**d: #144 PCと走行体のデータのやり取り

↓ 逆ゥーーーー！！

Clo**se**d: #144 PCと走行体のデータのやり取り

2019-08-16 12:37 UTC, Tatsumi0000 commented
> `serialOpen` はあるのに、`serialClose` がないのが気になる
> いっそ、Bluetoothクラスのメンバー変数としてFILEポインタを閉じ込めて
> デストラクタで解放させるように変更した方が安全な気がする。
> 
> まぁ、シリアル通信はメインタスクが終了するまで動き続けるから
> 些細な話かもしれないけど

FILEポインタを使った後に，開放していないと不安よな．
西田メンバ変数でFILEポインタを閉じ込めて，デストラクタで開放します．

2019-08-16 12:39 UTC, Tatsumi0000 commented
> Clo**es**d: #144 PCと走行体のデータのやり取り
> 
> ↓ 逆ゥーーーー！！
> 
> Clo**se**d: #144 PCと走行体のデータのやり取り

次こそ，修正したンゴ．

2019-08-20 07:27 UTC, Tatsumi0000 commented
> `serialOpen` はあるのに、`serialClose` がないのが気になる
> いっそ、Bluetoothクラスのメンバー変数としてFILEポインタを閉じ込めて
> デストラクタで解放させるように変更した方が安全な気がする。
> 
> まぁ、シリアル通信はメインタスクが終了するまで動き続けるから
> 些細な話かもしれないけど

人生で初めてデストラクタを書いてみました．
レビューをよろしくお願いします．

2019-08-21 09:50 UTC, Tatsumi0000 commented
C++っぽくnullptrにしてみた．

2019-08-23 08:06 UTC, Oiwane reviewed
1つだけ気になったところがありました

2019-08-23 08:06 UTC, Oiwane commented on src/module/api/Bluetooth.cpp
> +  if(bt == NULL) {
ここは `nullptr` にしなくてもいいのでしょうか

2019-08-23 08:16 UTC, Tamiyas commented on src/module/api/Bluetooth.cpp
> +  if(bt == NULL) {
nullptrの型の右辺値は、bool型右辺値に変換できるから
`if(!bt) { ... }` でもOKだね。

2019-08-23 08:27 UTC, Tatsumi0000 commented on src/module/api/Bluetooth.cpp
> +  if(bt == NULL) {
修正したンゴ．

2019-08-23 08:54 UTC, merged