closed #193 複数回まわして色識別する機能を追加する
KatLab-MiyazakiUniv/etrobocon2019 pull request #194
Opened 2019-08-21 09:49 UTC by match97

### 変更点
複数回まわして色識別する機能を追加
### 実機テストの結果（実機テストが必要な場合）
 - 怪しいところはあったが、色識別できた。

2019-08-22 04:46 UTC, Tatsumi0000 requested changes
多分，clang-formatで整形していないと思います．（してたらごめん）
ドキュメント（コメント）を書きましょう．書き方は，他のプログラムを参考にしてください．
後，
> ### 実機テストの結果（実機テストが必要な場合）
> 
>     * 怪しいところはあったが、色識別できた。
もう少し詳しく書いてほしいです．
例えば，成功率，○色の検知は怪しい．とか…

2019-08-22 04:46 UTC, Tatsumi0000 commented on src/module/api/core/Controller.cpp
> +  int determinNum = 3;
```cpp
int determinNum = 3;
```
ここ
```cpp
static const int determinNum = 3;
```
するとかっこよくない？
`determinNum`は，このファイル内でしか使ってないし定数だから🧐

2019-08-22 04:46 UTC, Tatsumi0000 commented on src/module/api/core/Controller.cpp
> +        white += 1;
```cpp
white += 1;
```
ここ，（他の似たようなところもだけど）
```cpp
white++;
```
と書かないところにこだわりを感じました．
（自分はありだと思います 🙄）

2019-08-22 05:42 UTC, match97 commented
> 多分，clang-formatで整形していないと思います．（してたらごめん）
> ドキュメント（コメント）を書きましょう．書き方は，他のプログラムを参考にしてください．
> 後，
> 
> > ### 実機テストの結果（実機テストが必要な場合）
> > ```
> > * 怪しいところはあったが、色識別できた。
> > ```
> 
> もう少し詳しく書いてほしいです．
> 例えば，成功率，○色の検知は怪しい．とか…

clang-formatで整形し直しました。できているかどうか怪しいですが。
コメントを付けました。
ガバガバ実機テストの記述を、訂正しました。

2019-08-22 05:43 UTC, match97 commented on src/module/api/core/Controller.cpp
> +  int determinNum = 3;
かっこよくしました。(^^)

2019-08-22 05:45 UTC, match97 commented on src/module/api/core/Controller.cpp
> +        white += 1;
改めてみると違和感を感じたので下の書き方に訂正しました。

2019-08-22 05:56 UTC, Tatsumi0000 approved these changes
＼clang-formatも効いてて素晴らしいコードだと思います．／
＊　　　+　　 巛＼
　　　　　　　 〒｜ +
　　　+　　　。｜｜
　＊　　 +　　 / /
　　　 ∧＿∧ / /
　　　(´∀｀/ /　+
　　　/~　　　｜
　　 /ュﾍ　　 ｜＊
　+ (＿〕)　　｜
　　　　/　　 ｜　 +
ｶﾞﾀﾝ　 /　/ヽ ｜
　||| /　/　| ｜|||
―――――――――――
![LGTM](https://lgtmoon.herokuapp.com/images/2552)

2019-08-22 05:56 UTC, Tatsumi0000 commented on src/module/api/core/Controller.cpp
> +//色検出を繰り返し行い,ある色がdetermineNum(以下だと３)回検出されれば返す関数である
🥰

2019-08-23 08:25 UTC, Tamiyas requested changes
if文が多くて、少しコードスメルがしますが
概ね間違っていないので良いと思います！

`tslpTsk` だけ直しておいてください。

2019-08-23 08:25 UTC, Tamiyas commented on src/module/api/core/Controller.cpp
> +  while (1) {
`tslpTsk(4)` 忘れてませんか

2019-08-23 11:01 UTC, sigenaga approved these changes
異常なしであります(｀・ω・´)

2019-08-23 12:37 UTC, match97 commented on src/module/api/core/Controller.cpp
> +  while (1) {
`tslpTsk(4)`を追加しました。

2019-08-29 01:21 UTC, sigenaga approved these changes
誤字とかはないと思います

2019-08-29 02:26 UTC, Oiwane requested changes

2019-08-29 02:26 UTC, Oiwane commented on src/module/api/core/Controller.cpp
> +    Color color = this->hsvToColor(status);
今更ながら気付きましたが、これcolorの値変わってませんよね？となると多数決にならないかもです

2019-08-29 02:26 UTC, Oiwane commented on src/module/api/core/Controller.cpp
> +  int max = counter[0];
maxの型をColor型にしたら戻り値の指定が楽なのでは？

2019-08-29 18:26 UTC, match97 commented on src/module/api/core/Controller.cpp
> +    Color color = this->hsvToColor(status);
引数で受け取るのではなく、関数内で`getHsv()`を呼び出すことによってcolorの値が変わるように修正。

2019-08-29 18:52 UTC, match97 commented on src/module/api/core/Controller.cpp
> +  int max = counter[0];
楽、、なんかな？`max`をColor型にしたら`countor[]`もColor型にせんと型が違うから比較できんしどうすればいいか分からなかった。
このままじゃだめなん？

2019-08-30 03:41 UTC, Oiwane commented on src/module/api/core/Controller.cpp
> +  int max = counter[0];
ん？`counter`はint型のままで良いと思うよ？if文の条件式を
```cpp
if ( counter[static_cast<int>(max)] < counter[i] )
```
ってすれば良いんじゃないかと。

2019-08-30 04:04 UTC, Oiwane commented on src/module/api/core/Controller.cpp
> +  int max = counter[0];
訂正

`max` はint型で `counter` の添え字としておいて、戻り値をColor型にキャストした方がいいかも

2019-08-30 05:18 UTC, match97 commented on src/module/api/core/Controller.cpp
> +  int max = counter[0];
なるほど、そのように変更しました。

2019-08-30 05:27 UTC, Oiwane commented on src/module/api/core/Controller.cpp
> +  int max = counter[0];
for文もif文も要らんよ

2019-08-30 05:30 UTC, match97 commented on src/module/api/core/Controller.cpp
> +  int max = counter[0];
164行から削除したぞ

2019-08-30 05:50 UTC, Oiwane commented on src/module/api/core/Controller.cpp
> +  int max = counter[0];
よく見たらその前の問題だった
ごめん、説明がへたすぎてうまく伝わってなかったみたい

僕の考えとしては
`max` を `counter` の最大値の添え字にしたらいいんじゃないかと思ったのね
理由としては後半のif文が無駄かなと思ったから
で、`max` が `counter` の最大値の添え字になるんなら `max` をColor型にキャストすればそれ自体が戻り値になるからfor文もif文もいらんか、ってなって

> 164行目からのfor文もif文も要らんよ

って言ったわけ
でもよく見たら `max` に `counter` の値が入ってるからいろいろと訳わからないことになってた。すみません

2019-08-30 06:29 UTC, match97 commented on src/module/api/core/Controller.cpp
> +  int max = counter[0];
結局どうするのがベストなん？
最初のif文があるやつにもどしたらいけん？

2019-08-30 07:01 UTC, Oiwane commented on src/module/api/core/Controller.cpp
> +  int max = counter[0];
> 最初のif文があるやつにもどしたらいけん？

個人的に見づらいと感じただけなので提案しただけ
戻しても良いのでは？
他に指摘があるようなら考えないといけないと思うけど

2019-08-30 07:37 UTC, match97 commented on src/module/api/core/Controller.cpp
> +  int max = counter[0];
`git commit -m "sorry,Mr.大岩根"`

2019-08-30 07:38 UTC, Oiwane commented on src/module/api/core/Controller.cpp
> +  int max = counter[0];
OK, Mr match97

2019-09-03 06:06 UTC, Oiwane approved these changes
変更お疲れ様でした
遅れてすみませんでした

2019-09-07 09:44 UTC, korosuke613 approved these changes
Litmus

2019-09-07 09:44 UTC, korosuke613 commented on src/module/api/core/Controller.cpp
> +  static const int determineNum = 7;
この6,7というマジックナンバーですが、メソッドのデフォルト引数にして、指定できるようにしても良いかもしれません。

2019-09-07 09:44 UTC, korosuke613 commented on test/dummy/Controller.h
> +   return this->hsvToColor(hsv);
うわーおディスポインタ
俺は知識不足なせいでなぜthisを使う必要があるかわからない。
教えて @Tamiyas ！！

2019-09-07 09:58 UTC, Tamiyas commented on test/dummy/Controller.h
> +   return this->hsvToColor(hsv);
これは、使っても使わなくても同じですな
好み？

2019-09-07 10:00 UTC, Tamiyas commented on src/module/api/core/Controller.cpp
> +  for (int i = 1; i < 6; i++) {
ここが、6で固定なのが気になります

2019-09-07 10:02 UTC, korosuke613 commented on src/module/api/core/Controller.cpp
> +  for (int i = 1; i < 6; i++) {
私も、気になります！！！！（ELTS)

2019-09-07 10:03 UTC, korosuke613 requested changes
やっぱりマジックナンバー(6,7のこと)をなんとかしてほしい感がありますね

2019-09-08 05:01 UTC, match97 commented
> やっぱりマジックナンバー(6,7のこと)をなんとかしてほしい感がありますね

デフォルト引数にして指定できるように変更しました。

2019-09-08 05:09 UTC, korosuke613 approved these changes
やりますねぇ！
![LGTM](https://lgtmoon.herokuapp.com/images/22472)

2019-09-08 05:14 UTC, match97 commented
> if文が多くて、少しコードスメルがしますが
> 概ね間違っていないので良いと思います！
> 
> `tslpTsk` だけ直しておいてください。

変更後の報告がなかったです。申し訳ございません。

2019-09-09 04:25 UTC, Tamiyas approved these changes

2019-09-09 04:25 UTC, merged