アームに関する処理を追加
KatLab-MiyazakiUniv/etrobocon2019 pull request #204
Opened 2019-09-11 08:23 UTC by Oiwane

### 変更点
 - アームに関する処理を追加した

### 実機テストの結果
 - アームを上下に動かせました

2019-09-11 08:31 UTC, match97 requested changes
countにどこまで入れていいかのコメントがあれば親切だと思う（小並感）

2019-09-11 08:40 UTC, Oiwane commented
@match97 
カラーセンサーが地面に対して垂直に向いているときを0としたとき、アームが上がるモータの回転角度（？）の最大値が40くらい、最小値が-20くらいでした。

2019-09-11 08:42 UTC, match97 commented
> @match97
> カラーセンサーが地面に対して垂直に向いているときを0としたとき、アームが上がるモータの回転角度（？）の最大値が40くらい、最小値が-20くらいでした。

2019-09-11 08:43 UTC, match97 approved these changes

2019-09-13 06:28 UTC, Tatsumi0000 requested changes
もっと，コメントを書いてほしいと思いマンタ🙄
修正お願いします🙇‍♂️

2019-09-13 06:28 UTC, Tatsumi0000 commented on src/module/api/core/Controller.cpp
> +  }
```cpp
  if(count >= 0) {
    this->setArmMotorPwm(pwm);
    while(this->getArmMotorCount() < count) {
    }
  } else {
    this->setArmMotorPwm(-pwm);
    while(this->getArmMotorCount() > count) {
    }
  }
```
ここの処理，もっとオシャンティーにできそうな気がするけど思いつかないorz

2019-09-13 06:28 UTC, Tatsumi0000 commented on src/module/api/core/Controller.cpp
> +  int pwm = 10;
```cpp
int pwm = 10;
```
私気になります．
`pwm`を引数で受取るようにして，デフォルト引数で`10`としたほうがいいと思いマンタ．

2019-09-13 06:35 UTC, Tatsumi0000 commented
そいえば，1つ気になることがありました．
アームの上げ下げの実機テストをするときに実際にブロックをアームにセットして試しましたか？
（もし試してたらごめんなさい🙇‍♂️）
結構勢いよくアームを動かさないと，
ブロックを巻き込んだまま次の処理に移りますよ．

2019-09-13 07:04 UTC, Oiwane commented on src/module/api/core/Controller.cpp
> +  int pwm = 10;
指摘された箇所を修正しました

2019-09-13 07:20 UTC, Oiwane commented
@Tatsumi0000 
> もっと，コメントを書いてほしいと思いマンタ🙄

確かに分かりづらかったです。
コメントを追加しました。

> アームの上げ下げの実機テストをするときに実際にブロックをアームにセットして試しましたか？

一応、試しましたが、試したブロックは紙（？）を張り付けたブロックでした。
ビニールテープを巻いたブロックでテストし忘れてました。
ビニールテープを巻いてあるブロックで試した場合、ビニールテープの表面に引っかかって巻き込んだままになる可能性があります。
明日、試して結果を報告したいと思います。

2019-09-13 08:02 UTC, Tatsumi0000 commented
よろしくお願いします( ﾟ∀ﾟ)

2019-09-14 05:32 UTC, Oiwane commented
@Tatsumi0000 
![DSC_0092](https://user-images.githubusercontent.com/44086176/64903801-8e5ae380-d6fa-11e9-98c5-f457e8597c41.JPG)

この3つのブロックで試してみました。
緑のブロックがビニールテープで、ほかの二つは表面がなめらかなものです。

黒　https://photos.app.goo.gl/pFCN3eVw9fhSv4QCA
緑　https://photos.app.goo.gl/GnaTzsn4MU19xfqJ7
青　https://photos.app.goo.gl/DMjBDLdAkHnCjNMj8

動画を見ると緑が若干怪しいですが、一応は動かすことができています。

また、ブロックがアームから完全に離れていないと感じるかもしれませんが、
ブロックを設置するときは

1. 走行体を前に少し進ませる
2. アームを動かしてブロックを設置する
3. 走行体を元の位置に戻す

という流れで動かすつもりなので離れる予定です。そちらも試してます。

2019-09-16 05:26 UTC, korosuke613 approved these changes
変更箇所がわかりづらいから全部 ✅️できたかあやしいんだけど、
![LGTM](https://lgtmoon.herokuapp.com/images/27428)

2019-09-16 05:26 UTC, korosuke613 commented on src/module/api/core/Controller.cpp
> +  }
ガチればもっと最適化できそうだけど、難解なコードになりそうだからこれで良いんじゃね？

2019-09-17 03:34 UTC, sigenaga approved these changes
異常なしであります(｀・ω・´)

2019-09-17 05:46 UTC, Tatsumi0000 approved these changes
ナイスバルク！！！
![LGTM](https://lgtmoon.herokuapp.com/images/29176)

2019-09-21 02:37 UTC, merged