closed #199 ビンゴを飛ばし、ガレージ駐車まで行うクラスの作成
KatLab-MiyazakiUniv/etrobocon2019 pull request #205
Opened 2019-09-16 15:33 UTC by match97

### 変更点
- 進入ラインからビンゴを無視してガレージ駐車まで行うクラスの作成
- ブロックを避けつつ移動するように作成する
- L,Rコース版を作る
- parkingクラス内の処理が一つ終わるごとに音が鳴ってかっこ悪かったので削除
- parkingクラスの軽微な変更(L,Rコース)

### parkingクラスのLコースの変更点
今までのだと⑧の右上の緑サークルの下半分の緑を認識しまっすぐ進むと、ガレージ前の青線が認識できないことあった。
緑を認識後、少し進み10度反時計回りに回頭することにより緑サークルの下半分を認識した場合でも確実にその青線を認識可能に変更した。

### parkingクラスのRコースの変更点
今までは④の左上の青サークルを認識後少し進んで90度反時計回りに回頭し、ガレージ前の黒線を認識後し90度時計回りに回頭していたが、青サークルの認識場所によっては一回目の回頭場所がずれ黒線を認識しない場合があった。
一回目の回頭を45度反時計回りの回頭にすることにより、一回目の回頭場所がずれても確実にガレージ前の黒線を認識するように変更した。

### 実機テストの結果（実機テストが必要な場合）
 - Rコース
https://photos.google.com/photo/AF1QipMA2MN23S8ndyfOVu8VoYwE_dWxlROGRL_II5oO
- Lコース
https://photos.google.com/photo/AF1QipNhExB__zsx59u39FEiakRu21-ko7wTSEUF580c

2019-09-17 03:36 UTC, sigenaga approved these changes
異常なしであります(｀・ω・´)

2019-09-17 05:24 UTC, Oiwane requested changes
動画を見ることができません

あとコードの方もちょっとですが気になる点がありました

2019-09-17 05:24 UTC, Oiwane commented on src/module/MoveDirectGarage.cpp
> +void MoveDirectGarage::MoveDirectGarageL()
関数名が大文字から始まってますよ

2019-09-17 05:24 UTC, Oiwane commented on src/module/MoveDirectGarage.cpp
> +void MoveDirectGarage::MoveDirectGarageR()
関数名が大文字から始まってますよ

2019-09-17 05:24 UTC, Oiwane commented on src/module/MoveDirectGarage.h
> +      void MoveDirectGarageL();
関数名が大文字から始まってますよ

2019-09-17 05:24 UTC, Oiwane commented on src/module/MoveDirectGarage.h
> +      void MoveDirectGarageR();
関数名が大文字から始まってますよ

2019-09-17 05:58 UTC, Oiwane approved these changes
訂正の確認をしました

2019-09-26 04:55 UTC, Tatsumi0000 approved these changes
動画見ました．
きれいに動いていたのでいいと思います．

2019-09-26 04:55 UTC, Tatsumi0000 commented on src/module/MoveDirectGarage.cpp
> +//このクラスが使用されないことを願う
確かにその通り．

2019-09-26 09:16 UTC, korosuke613 approved these changes
![LGTM](https://lgtmoon.herokuapp.com/images/15606)

2019-09-27 15:57 UTC, closed without merging