bluetooth周りを修正
KatLab-MiyazakiUniv/etrobocon2019 pull request #214
Opened 2019-09-26 15:57 UTC by korosuke613

### 変更点

### 実機テストの結果（実機テストが必要な場合）
 - 例: 10回走行させた平均値を書く
 - 例: 誤差率 [%] を書く
 - 例: 前回の手法との差を書く

#### 誤差率の計算式
誤差率 = （「測定値」 - 「理論値」） / 「理論値」 * 100

2019-09-26 16:18 UTC, Tamiyas approved these changes
いいよ！

2019-09-26 16:19 UTC, arimakaoru approved these changes

2019-09-26 16:36 UTC, Tatsumi0000 approved these changes
平木場節の効いた素晴らしいコードだと思います．
![LGTM](https://lgtmoon.herokuapp.com/images/30158)

2019-09-27 06:18 UTC, match97 approved these changes

2019-09-27 06:20 UTC, Tamiyas requested changes
app.cppの7行目を消さないとビルドが通らない
フェッチしてみて

2019-09-27 06:42 UTC, merged