closed #212 Rcourseを選択した時に。。。
KatLab-MiyazakiUniv/etrobocon2019 pull request #217
Opened 2019-09-26 16:18 UTC by match97

### 変更点

### 実機テストの結果（実機テストが必要な場合）
 - 例: 10回走行させた平均値を書く
 - 例: 誤差率 [%] を書く
 - 例: 前回の手法との差を書く

#### 誤差率の計算式
誤差率 = （「測定値」 - 「理論値」） / 「理論値」 * 100

2019-09-26 16:41 UTC, Tatsumi0000 approved these changes
[こっち](https://github.com/KatLab-MiyazakiUniv/etrobocon2019/pull/205)で見たので，いいと思います．
[あの処理](https://github.com/KatLab-MiyazakiUniv/etrobocon2019/pull/205)をRコースのときにするってことだと理解しマンタ．
![LGTM](https://lgtmoon.herokuapp.com/images/28545)

2019-09-27 15:58 UTC, Tamiyas approved these changes
きれいに行くのを見ました
だから、OKとします

2019-09-27 16:29 UTC, Oiwane requested changes
mergeできないようにロックしておきます。
by松浦

2019-09-27 16:31 UTC, match97 commented
> mergeできないようにロックしておきます。
> by松浦

mergeしてしまうとLコース用のPIDが消えてしまうため

2019-09-28 14:39 UTC, match97 commented
> mergeできないようにロックしておきます。
> by松浦


もうmergeしてもらってもかまわんぞ

2019-10-02 15:42 UTC, merged

2019-10-02 15:42 UTC, korosuke613 commented
GOODJOB