[WIP] closed #239 LコースとRコースのPID値を切り替えられるようにした
KatLab-MiyazakiUniv/etrobocon2019 pull request #240
Opened 2019-10-20 14:21 UTC by korosuke613

### 変更点
LコースとRコースのPID値を切り替えられるようにした

### 実機テストの結果（実機テストが必要な場合）
 - やってないンゴ
 - だれかやって（懇願）

2019-10-20 14:26 UTC, match97 approved these changes
てすといがいはいいとおもいます。==（^ = ^）== （^ = ^）==（^ = ^）==（^ = ^）==（^ = ^）==

2019-10-23 06:14 UTC, sigenaga approved these changes
異常なしだと思います…

2019-10-24 12:45 UTC, Oiwane approved these changes
良いと思いました

2019-10-24 13:10 UTC, Tamiyas requested changes
なんか気持ち悪いので、Request changesにします。

2019-10-24 13:10 UTC, Tamiyas commented on src/module/NormalCourse.cpp
> +  const std::array<NormalCourseProperty, arraySize>& normalCourseProperty = isLeftCourse ? normalCoursePropertyL : normalCoursePropertyR;
`isLeftCourse` の値が実行時に決まるので、ここは `constexpr` にならないですね

`isLeftCourse` の値がコンパイル時に決まれば、C++17で導入されたconstexpr if文が使えるんだけどね

2019-10-24 13:10 UTC, Tamiyas commented on src/module/Pid.h
>  // PID制御のみで用いる定数をまとめた構造体
`ConstPidGain` と重複しているのが嫌ですね...

2019-10-24 13:10 UTC, Tamiyas commented on src/module/NormalCourse.cpp
> +  const std::array<NormalCourseProperty, arraySize>& normalCourseProperty = isLeftCourse ? normalCoursePropertyL : normalCoursePropertyR;
`isLeftCourse` の値が実行時に決まるので、この処理は `constexpr` にならないですね。

もし `isLeftCourse` がコンパイル時に決まれば、C++17から導入されたconstexpr if文が使えるんだけどね

2019-10-24 13:13 UTC, korosuke613 commented on src/module/NormalCourse.cpp
> +  const std::array<NormalCourseProperty, arraySize>& normalCourseProperty = isLeftCourse ? normalCoursePropertyL : normalCoursePropertyR;
`isLeftCourse`は実行時に決まるので無理でつ...

2019-10-24 13:14 UTC, korosuke613 commented on src/module/Pid.h
>  // PID制御のみで用いる定数をまとめた構造体
fix 0cffd11872b08b3050dc85d5de52e9d7826036a6

2019-10-24 13:14 UTC, korosuke613 commented on src/module/NormalCourse.cpp
> +  const std::array<NormalCourseProperty, arraySize>& normalCourseProperty = isLeftCourse ? normalCoursePropertyL : normalCoursePropertyR;
`isLeftCourse`は実行時に決まるので無理でつ...

2019-10-24 13:15 UTC, Tamiyas approved these changes
ok

2019-10-24 13:17 UTC, merged