[WIP] closed #232 ライントレース時に速度制御を行わないようにした
KatLab-MiyazakiUniv/etrobocon2019 pull request #241
Opened 2019-10-20 14:37 UTC by korosuke613

### 変更点
ライントレース時に速度制御を行わないようにした。

`baseSpeed`の値はもともと640であったので、これをPWM75%と設定し、
他の値もそれに伴い変更した。
![image](https://user-images.githubusercontent.com/20027695/67161122-6cf0b580-f392-11e9-8fca-93db1bff76c2.png)
こんな感じ

### 実機テストの結果（実機テストが必要な場合）
 - まだどす（舞子）

2019-10-23 06:11 UTC, sigenaga approved these changes
異常なしであります(｀・ω・´)

2019-10-24 10:48 UTC, match97 approved these changes

2019-10-24 11:40 UTC, korosuke613 commented on src/module/NormalCourse.cpp
> +  int baseSpeed = 75;
```suggestion
  int baseSpeed = 70;
```

2019-10-24 13:34 UTC, match97 approved these changes
Maybe that can help you.

2019-10-28 03:06 UTC, korosuke613 commented on src/module/NormalCourse.cpp
> +  const std::array<NormalCourseProperty, arraySize>& normalCourseProperty
```suggestion
  // LコースならLコースのPID値を採用する。RコースならRコースのPID値を採用する。
  const std::array<NormalCourseProperty, arraySize>& normalCourseProperty
```

2019-10-28 06:45 UTC, Tatsumi0000 requested changes
レビューしました．
よろしくおねがいします．

2019-10-28 06:45 UTC, Tatsumi0000 commented on src/module/NormalCourse.cpp
> +  const std::array<NormalCourseProperty, arraySize>& normalCourseProperty
```suggestion
  const std::array<NormalCourseProperty, arraySize> normalCourseProperty
```

こっちのほうが良いって@Tamiyasが言ってた．

2019-10-28 06:48 UTC, Tatsumi0000 approved these changes
ナイスコード！！！
![LGTM](https://lgtmoon.herokuapp.com/images/16130)

2019-10-29 07:29 UTC, merged