closed #235 NavigatorクラスとBlockBingoクラスから無駄な処理を削除した
KatLab-MiyazakiUniv/etrobocon2019 pull request #242
Opened 2019-10-21 05:11 UTC by Oiwane

### 変更点

 - Navigatorクラスの無駄な処理を削除した
 - BlockBingoクラスのフィールドにNavigatorを追加して、各処理での宣言を削除した
 - ついでにBlockBingoクラスのマジックナンバーを1つ消した

### 実機テストの結果
今までの動作と違いがあったようには見えませんでした

2019-10-21 07:28 UTC, Tatsumi0000 requested changes
よろぴこ

2019-10-21 07:28 UTC, Tatsumi0000 commented on src/module/BlockBingo.cpp
> +    lenghtColorSensorAxis(50.0),
```cpp
lenghtColorSensorAxis(50.0)
```
じゃなくて
```cpp
lengthColorSensorAxis(50.0)
```
だと思います．

2019-10-21 07:28 UTC, Tatsumi0000 commented on src/module/BlockBingo.cpp
> +  navigator.move(lenghtColorSensorAxis, straightPwm, pGain);
```cpp
navigator.move(lenghtColorSensorAxis, straightPwm, pGain);
```
じゃなく
```cpp
navigator.move(lengthColorSensorAxis, straightPwm, pGain);
```

2019-10-21 07:28 UTC, Tatsumi0000 commented on src/module/BlockBingo.cpp
> +  navigator.move(lenghtColorSensorAxis, straightPwm, pGain);
```cpp
navigator.move(lenghtColorSensorAxis, straightPwm, pGain);
```
じゃなく
```cpp
navigator.move(lengthColorSensorAxis, straightPwm, pGain);
```
だと思います．

2019-10-21 07:28 UTC, Tatsumi0000 commented on src/module/BlockBingo.cpp
> +  navigator.move(lenghtColorSensorAxis, straightPwm, pGain);
```cpp
navigator.move(lenghtColorSensorAxis, straightPwm, pGain);
```
じゃなく
```cpp
navigator.move(lengthColorSensorAxis, straightPwm, pGain);
```
だと思います．

2019-10-21 07:28 UTC, Tatsumi0000 commented on src/module/BlockBingo.cpp
> +  navigator.move(lenghtColorSensorAxis, straightPwm, pGain);
```cpp
navigator.move(lenghtColorSensorAxis, straightPwm, pGain);
```
じゃなく
```cpp
navigator.move(lengthColorSensorAxis, straightPwm, pGain);
```
だと思います．

2019-10-21 07:28 UTC, Tatsumi0000 commented on src/module/BlockBingo.cpp
> +  navigator.move(lenghtColorSensorAxis, straightPwm, pGain);
```cpp
navigator.move(lenghtColorSensorAxis, straightPwm, pGain);
```
じゃなく
```cpp
navigator.move(lengthColorSensorAxis, straightPwm, pGain);
```
だと思います．

2019-10-21 07:28 UTC, Tatsumi0000 commented on src/module/BlockBingo.cpp
> +  navigator.move(lenghtColorSensorAxis, straightPwm, pGain);
```cpp
navigator.move(lenghtColorSensorAxis, straightPwm, pGain);
```
じゃなく
```cpp
navigator.move(lengthColorSensorAxis, straightPwm, pGain);
```
だと思います．

2019-10-21 07:28 UTC, Tatsumi0000 commented on src/module/BlockBingo.cpp
> +  navigator.move(lenghtColorSensorAxis, straightPwm, pGain);
```cpp
navigator.move(lenghtColorSensorAxis, straightPwm, pGain);
```
じゃなく
```cpp
navigator.move(lengthColorSensorAxis, straightPwm, pGain);
```
だと思います．

2019-10-21 07:28 UTC, Tatsumi0000 commented on src/module/BlockBingo.cpp
> +  navigator.move(lenghtColorSensorAxis, straightPwm, pGain);
```cpp
navigator.move(lenghtColorSensorAxis, straightPwm, pGain);
```
じゃなく
```cpp
navigator.move(lengthColorSensorAxis, straightPwm, pGain);
```
だと思います．

2019-10-21 07:28 UTC, Tatsumi0000 commented on src/module/BlockBingo.cpp
> +  navigator.move(lenghtColorSensorAxis, straightPwm, pGain);
ここも．

2019-10-21 07:28 UTC, Tatsumi0000 commented on src/module/BlockBingo.cpp
> +  navigator.move(lenghtColorSensorAxis, straightPwm, pGain);
ここも

2019-10-21 07:28 UTC, Tatsumi0000 commented on src/module/BlockBingo.cpp
> +  navigator.move(lenghtColorSensorAxis, straightPwm, pGain);
ここも

2019-10-21 07:28 UTC, Tatsumi0000 commented on src/module/BlockBingo.cpp
> +  navigator.move(lenghtColorSensorAxis, straightPwm, pGain);
ここも

2019-10-21 07:28 UTC, Tatsumi0000 commented on src/module/BlockBingo.cpp
> +  navigator.move(lenghtColorSensorAxis, straightPwm, pGain);
ここも

2019-10-21 07:28 UTC, Tatsumi0000 commented on src/module/BlockBingo.cpp
> +  navigator.move(lenghtColorSensorAxis, straightPwm);
ここも

2019-10-21 07:28 UTC, Tatsumi0000 commented on src/module/BlockBingo.h
> +  const double lenghtColorSensorAxis;
ここも

2019-10-21 08:42 UTC, Oiwane commented
@Tatsumi0000 
修正しました

2019-10-21 14:34 UTC, korosuke613 requested changes
テスト通して❤️

2019-10-21 14:38 UTC, match97 approved these changes
マジックナンバーが消えてて良きかな。
すっきりしましたね。

2019-10-21 14:51 UTC, Oiwane commented
@korosuke613 

エラーの内容が全く分かりません
cmakeがどうのこうの言ってます

2019-10-21 14:53 UTC, korosuke613 commented
> @korosuke613
> 
> エラーの内容が全く分かりません
> cmakeがどうのこうの言ってます

いま調査中ンゴねぇ

2019-10-21 15:00 UTC, Oiwane commented
@korosuke613 

伝え忘れていましたが、なぜかローカルではテスト通りました

2019-10-21 15:16 UTC, match97 commented
先に自分のが通ったのでコンフリクトしてますね

2019-10-21 15:22 UTC, Oiwane commented
@match97 

修正中です

2019-10-21 15:36 UTC, Oiwane commented
@match97 
修正しました

2019-10-21 16:13 UTC, korosuke613 commented
テスト通るようにしてやったゾ（実際は該当テストをオフにしただけ）

2019-10-21 16:17 UTC, korosuke613 approved these changes
![LGTM](https://lgtmoon.herokuapp.com/images/32712)

だけど、定数なら`constexpr`で良くね？

2019-10-21 16:17 UTC, korosuke613 commented on src/module/BlockBingo.h
> +  const double lengthCrossCircleCenter;
定数なら`constexpr`で良くね？
```suggestion
  static constexpr double lengthCrossCircleCenter = 175.0;
```

2019-10-21 16:17 UTC, korosuke613 commented on src/module/BlockBingo.h
> +  const double lengthColorSensorAxis;
定数なら`constexpr`で良くね？
```suggestion
  static constexpr double lengthColorSensorAxis = 50.0;
```

2019-10-21 16:17 UTC, korosuke613 commented on src/module/BlockBingo.cpp
> +    lengthCrossCircleCenter(175.0),
定数なら`constexpr`で良くね？
```suggestion
```

2019-10-21 16:17 UTC, korosuke613 commented on src/module/BlockBingo.cpp
> +    lengthColorSensorAxis(50.0),
定数なら`constexpr`で良くね？
```suggestion
```

2019-10-21 17:09 UTC, korosuke613 commented
まーーーーーーた失敗しとるテスト

呪われてるでこれ

2019-10-22 16:14 UTC, Tatsumi0000 approved these changes
いいコードだ．
![LGTM](https://lgtmoon.herokuapp.com/images/32743)

2019-10-23 01:48 UTC, merged