closed #248 指定した距離だけライントレースをする関数を作成した
KatLab-MiyazakiUniv/etrobocon2019 pull request #251
Opened 2019-10-29 07:19 UTC by Oiwane

### 変更点
 - Navigatorクラスに`traceBlackLine`関数を追加した
 - テストコードを追加した
 - 実機テストをした（下に動画あり）

### 実機テストの結果
動画 https://photos.app.goo.gl/iAnJu8qzoPaVuinx8

条件
 - 直進用Pゲイン : 0.70
 - ライントレース用Pゲイン : 0.10
 - ブロックを設置後、止まらずにバックしていきますが、これは今回関係ないのでスルーしてください

2019-10-29 07:36 UTC, Tatsumi0000 approved these changes
nice boat.
![LGTM](https://lgtmoon.herokuapp.com/images/27229)

2019-10-29 07:44 UTC, korosuke613 requested changes
WOWWOW!!!!

NOT LGTM!!!!!!!!!!😠😡😠

2019-10-29 07:44 UTC, korosuke613 commented on src/module/Navigator.cpp
> +void Navigator::traceBlackLine(double specifiedDistance, int pwm, double encoderPGain, double lineTracePGain, bool isLeft)
指定した距離だけでおっけーですか？

2019-10-29 07:44 UTC, korosuke613 commented on src/module/Navigator.cpp
> +  if(specifiedDistance < 0) {
```suggestion
  // 指定した距離に到達するまでTrue
  if(specifiedDistance < 0) {
```
みたいなコメントがほちぃ

2019-10-29 07:52 UTC, match97 reviewed
「指定した距離だけ移動する」的な意味を含むような関数名にしてほしい（小並感）

2019-10-29 08:18 UTC, Oiwane commented
@match97 
traceが「（道に沿って）進む」という意味があるので、関数名は「指定した距離だけ黒線に沿って進む」という意味になると思います。

2019-10-29 08:19 UTC, Oiwane commented on src/module/Navigator.cpp
> +void Navigator::traceBlackLine(double specifiedDistance, int pwm, double encoderPGain, double lineTracePGain, bool isLeft)
というと、色も指定する、ということですか？

2019-10-29 08:20 UTC, Oiwane commented on src/module/Navigator.cpp
> +  if(specifiedDistance < 0) {
追加しました

2019-10-29 08:28 UTC, match97 approved these changes
ちゃんとうごいていたのでいいとおもいました。

2019-10-29 08:55 UTC, match97 commented
> @match97
> traceが「（道に沿って）進む」という意味があるので、関数名は「指定した距離だけ黒線に沿って進む」という意味になると思います。

しらなかったです

2019-10-30 05:25 UTC, korosuke613 commented on src/module/Navigator.cpp
> +void Navigator::traceBlackLine(double specifiedDistance, int pwm, double encoderPGain, double lineTracePGain, bool isLeft)
色も指定できたら精度あがるくね？っておもったけど、実際距離だけで問題なさそう？

どうが見る限り大丈夫そうではあるが

2019-10-30 05:27 UTC, korosuke613 approved these changes
![LGTM](https://lgtmoon.herokuapp.com/images/9217)

2019-10-30 05:33 UTC, Oiwane commented on src/module/Navigator.cpp
> +void Navigator::traceBlackLine(double specifiedDistance, int pwm, double encoderPGain, double lineTracePGain, bool isLeft)
色まで考え出すとカメラシステムのコマンド生成が大変なことになるかな、と思い、実装していません。あと、仮に実装をした場合、終点が交点サークルである時にしかまともに使用できないため、実装する必要がないとも考えました。

2019-10-30 05:35 UTC, korosuke613 commented on src/module/Navigator.cpp
> +void Navigator::traceBlackLine(double specifiedDistance, int pwm, double encoderPGain, double lineTracePGain, bool isLeft)
そういえば走行隊は交点サークルの色情報持ってなかったね（忘れてたマン）

了解！

2019-10-31 06:37 UTC, merged