[WIP] closed #253 RGBを正規化し、PID値を調整
KatLab-MiyazakiUniv/etrobocon2019 pull request #254
Opened 2019-10-31 10:09 UTC by korosuke613

### 変更点
- RGBを正規化
- PID値を調整

### 実機テストの結果（実機テストが必要な場合）
それぞれ3回走らせた。3回ともGOAL。
- Rコースがだいたい22秒（URL）
- Lコースがだいたい24秒（URL）

2019-10-31 12:57 UTC, Tatsumi0000 requested changes
多分，`clang-format`効いてないと思うので整形おなしゃす．

2019-10-31 12:57 UTC, Tatsumi0000 commented on src/module/api/core/Controller.cpp
> +  return value;
```cpp
if(value >= max){
  return max;
}else if (value <= min){
  return min;
}
return value;
```
の方が処理早くなりそう（小並感）

2019-10-31 13:42 UTC, korosuke613 commented on src/module/api/core/Controller.cpp
> +  return value;
確蟹

2019-10-31 13:45 UTC, korosuke613 commented on src/module/api/core/Controller.cpp
> +  return value;
適用したンゴ
2ee39f4

2019-10-31 13:45 UTC, korosuke613 commented
> 多分，`clang-format`効いてないと思うので整形おなしゃす．

@Tatsumi0000 整形しますた

2019-10-31 13:56 UTC, Tatsumi0000 approved these changes
お疲れサマンサタバサ．
![LGTM](https://lgtmoon.herokuapp.com/images/18581)

2019-11-01 08:50 UTC, Oiwane requested changes
レビューしました

2019-11-01 08:50 UTC, Oiwane commented on src/module/api/core/Controller.cpp
> +int limit_max_min(const int value)
スネークケースになっているのは何かこだわりが？

2019-11-01 08:50 UTC, Oiwane commented on src/module/api/core/Controller.cpp
> +int limit_max_min(const int value)
正直、`limit_max_min`だとわかりずらいと思ったので
```suggestion
int limitRgbValue(const int value)
```
とかどうですか？

2019-11-02 11:09 UTC, korosuke613 commented on src/module/api/core/Controller.cpp
> +int limit_max_min(const int value)
PythonとC++行ったり来たりした結果！！

まあ`limit_max_min`はメソッドじゃなくてただの関数なんだけどね

2019-11-02 11:10 UTC, korosuke613 commented on src/module/api/core/Controller.cpp
> +  r = limit_max_min(static_cast<double>((rgb.r - R_MIN)) * 255 / (R_MAX - R_MIN));
```suggestion
  r = limitRgbValue(static_cast<double>((rgb.r - R_MIN)) * 255 / (R_MAX - R_MIN));
```

2019-11-02 11:10 UTC, korosuke613 commented on src/module/api/core/Controller.cpp
> +  g = limit_max_min(static_cast<double>((rgb.g - G_MIN)) * 255 / (G_MAX - G_MIN));
```suggestion
  g = limitRgbValue(static_cast<double>((rgb.g - G_MIN)) * 255 / (G_MAX - G_MIN));
```

2019-11-02 11:10 UTC, korosuke613 commented on src/module/api/core/Controller.cpp
> +  b = limit_max_min(static_cast<double>((rgb.b - B_MIN)) * 255 / (B_MAX - B_MIN));
```suggestion
  b = limitRgbValue(static_cast<double>((rgb.b - B_MIN)) * 255 / (B_MAX - B_MIN));
```

2019-11-02 11:13 UTC, korosuke613 commented on src/module/api/core/Controller.cpp
> +int limit_max_min(const int value)
THX MR. OOIWANE !!

2019-11-02 11:17 UTC, Oiwane approved these changes

2019-11-02 11:17 UTC, merged