[WIP] closed #255 ノーマルコース走行時の区間切替の際にふらつかないようにした
KatLab-MiyazakiUniv/etrobocon2019 pull request #256
Opened 2019-11-02 13:03 UTC by korosuke613

# 変更点
## ノーマルコース走行時の区間切替の際にふらつかないようにした
具体的に言うと`LineTracer::run()`の前に、`LineTracer::preRun()`を実行することで、旋回値`turnValue`が暴れないようにした。

デバッガで確認したところ、暴れなくなった。

## ControllerクラスのDummyにおいて、getBrightnessで得られる値がふらつくようにした。

### 実機テストの結果（実機テストが必要な場合）
 - デバッグで確認
 - （家でコーディングしたので）まだです。

2019-11-04 09:06 UTC, Tamiyas requested changes
確かにissueの動画を見る限り、分割した区間の境でふらついているように見えるが
ふらついていない区間もある。
結局のところ区間が変わる地点で、PIDの値であったり、前進値であったりの変化が起こるからふらつくんじゃないかな。この問題は、急激な値の変化を与えないように区間をさらに分割したり、急激に値を変化させないようにしたりして解決するんじゃないかと僕は思います。

最後に、ソースコードに気になる箇所があったので指摘しました。
WIPとのことですので、まだ開発途中であったのなら指摘は無視してください。

2019-11-04 09:06 UTC, Tamiyas commented on src/module/LineTracer.cpp
> +  }
`preRun` という名前の割に`run` しないのはなんで？
`controller` の `setLeftMotorPwm` と `setRightMotorPwm` を呼び出さないと動かないよ

2019-11-04 09:06 UTC, Tamiyas commented on src/module/NormalCourse.cpp
> +    lineTracer.preRun(ncp);
このコード要るだろうか？
結局のところ、`NormalCourseProperty` の `distance` を分割しているようにしか見えない。もし `preRun` で少しだけ進むようなことがあるのなら、 `run` で指定する距離にも影響が出てくると思う。

2019-11-10 08:21 UTC, korosuke613 commented on src/module/LineTracer.cpp
> +  }
`preRun`という名前は`run`する前にやる行動という意味で名付けたから走らせないのは正解。

名前が良くない可能性は大いにある。

2019-11-10 08:22 UTC, korosuke613 commented on src/module/NormalCourse.cpp
> +    lineTracer.preRun(ncp);
上でもコメントしたけど`preRun`で進むことはないから`distance`分割しているわけではない

2019-11-10 08:23 UTC, korosuke613 commented
@Tamiyas レビューしてくれてありがたかったけど、 #265 が良い感じだと思うのでこのプルリクは`close`しますぜ

2019-11-10 08:23 UTC, closed without merging