closed #292 速くなった
KatLab-MiyazakiUniv/etrobocon2019 pull request #294
Opened 2019-11-16 13:26 UTC by korosuke613

### チェックリスト
- 速くなった
- キャリブレーション中に電圧出るようにした。

### 変更点
- ノーマルコースPID値を変更
- 電圧でるようにした

### 実機テストの結果（実機テストが必要な場合）
 - 約1秒速くなった
- コースアウトもしない

2019-11-16 14:49 UTC, match97 approved these changes

2019-11-16 16:57 UTC, Tamiyas requested changes
速度を上げたんですね。走行タイムが上がって嬉しいです！

2019-11-16 16:57 UTC, Tamiyas commented on src/module/Calibrator.cpp
> +  Display::print(1, "Calibration, mV:%d, mA:%d", volt, amp);
17行目にも同じ記述があるけど、この記述には何か意味があるの？

2019-11-17 05:46 UTC, korosuke613 commented on src/module/Calibrator.cpp
> +  Display::print(1, "Calibration, mV:%d, mA:%d", volt, amp);
あ、これいらなくなったんだった

2019-11-17 05:46 UTC, korosuke613 commented on src/module/Calibrator.cpp
> +  Display::print(1, "Calibration, mV:%d, mA:%d", volt, amp);
```suggestion
```

2019-11-17 06:42 UTC, Tamiyas approved these changes
こんなに速度上げちゃっていいの
CS大会で宮大の意地を見せつけたいですね

2019-11-17 06:43 UTC, merged

2019-11-17 06:43 UTC, Tamiyas commented on src/module/Calibrator.cpp
> +  Display::print(1, "Calibration, mV:%d, mA:%d", volt, amp);
オッケー