closed #44
KatLab-MiyazakiUniv/etrobocon2019 pull request #45
Opened 2019-05-28 18:49 UTC by korosuke613

### 変更点
- CI環境を整備した。
- README.mdにバッジを追加した。

#### 参考
[Circle CI](https://circleci.com/workflow-run/46767f41-51b7-44df-be5a-87339e0329c2)
[Codecov](https://codecov.io/gh/KatLab-MiyazakiUniv/etrobocon2019/branch/enableCI)

2019-05-29 12:05 UTC, Tamiyas requested changes
README.mdにテストファイルの置き方を追加してください
他にも、ソースファイルの置き場とかの更新もしてくれると助かります

2019-05-29 12:10 UTC, Morichan commented
参考のCircleCIリンクが404です
直してくれると参考にできます

2019-05-29 12:18 UTC, korosuke613 commented
> 参考のCircleCIリンクが404です
> 直してくれると参考にできます

どうやらcircle ciにログインしてかつコントリビューターじゃないと見れないっぽいです。
とりあえずスクショを貼っておきました。
THX MORY

2019-05-29 12:18 UTC, korosuke613 commented
> 参考のCircleCIリンクが404です
> 直してくれると参考にできます

@Morichan 
どうやらcircle ciにログインしてかつコントリビューターじゃないと見れないっぽいです。
とりあえずスクショを貼っておきました。
THX MORY

2019-05-29 12:20 UTC, korosuke613 commented
@Tamiyas 

> README.mdにテストファイルの置き方を追加してください
やります。

> 他にも、ソースファイルの置き場とかの更新もしてくれると助かります
どういう意味ですか？

2019-05-29 12:24 UTC, Tamiyas commented
ごめんごめん
えっと、ソースファイルはmoduleフォルダに入れるんだよね
READMEを変更するならついでにソースファイルの置き場の記述も変えてもらおうと思ったんだ

2019-05-30 10:37 UTC, korosuke613 commented
> ごめんごめん
> えっと、ソースファイルはmoduleフォルダに入れるんだよね
> READMEを変更するならついでにソースファイルの置き場の記述も変えてもらおうと思ったんだ

@Tamiyas 
[修正](https://github.com/KatLab-MiyazakiUniv/etrobocon2019/pull/45/commits/9a76f20323c762d3f9a69fc6f6f6e01ba60286ed)しました。
レビューおなしゃす！

2019-05-30 12:17 UTC, Tamiyas requested changes
とりあえずレビューしました

2019-05-30 12:17 UTC, Tamiyas commented on README.md
> +1. Add Test after the class name.
Create a file named (class name) + "Test".

2019-05-30 12:17 UTC, Tamiyas commented on README.md
> +### Where is source code directory?
Where should you add your source files?
にしては？

2019-05-30 12:17 UTC, Tamiyas commented on README.md
> +### What is add test cases?
How to add test cases.
でいいような気がしてきた。

2019-05-30 12:17 UTC, Tamiyas commented on README.md
> +#### for example
For example
大文字にした方がいいかな？

2019-05-30 12:17 UTC, Tamiyas commented on README.md
> +#### rule
上をHow to ~にするならば、Ruleという項目は要らない

2019-05-30 12:17 UTC, Tamiyas commented on README.md
> +2. Put test code to `/test`.
Put the test file to '/test'.

2019-05-30 12:17 UTC, Tamiyas commented on README.md
> +Added Example class.
Create source codes that implement `Example` class.

2019-05-30 12:17 UTC, Tamiyas commented on README.md
> +Create test cases for Example class.
Create a test file for `Example` class.

2019-05-30 12:17 UTC, Tamiyas commented on README.md
> +Add `ExampleTest.cpp` to `/test`.
Put `ExampleTest.cpp` to `/test`.

2019-05-30 12:17 UTC, Tamiyas commented on README.md
> +#### testing
Execute test cases

2019-05-30 12:21 UTC, korosuke613 commented on README.md
> +#### for example
`####` は小文字スタートです

2019-05-30 12:27 UTC, korosuke613 commented on README.md
> +1. Add Test after the class name.
[修正](https://github.com/KatLab-MiyazakiUniv/etrobocon2019/pull/45/commits/ab63b96f4aceb921cbf3d31a304fa89f51c77ea0)しました。

2019-05-30 12:28 UTC, korosuke613 commented on README.md
> +### Where is source code directory?
[修正](https://github.com/KatLab-MiyazakiUniv/etrobocon2019/pull/45/commits/ab63b96f4aceb921cbf3d31a304fa89f51c77ea0)しました。

2019-05-30 12:28 UTC, korosuke613 commented on README.md
> +### What is add test cases?
[修正](https://github.com/KatLab-MiyazakiUniv/etrobocon2019/pull/45/commits/ab63b96f4aceb921cbf3d31a304fa89f51c77ea0)しました。

2019-05-30 12:28 UTC, korosuke613 commented on README.md
> +#### rule
[修正](https://github.com/KatLab-MiyazakiUniv/etrobocon2019/pull/45/commits/ab63b96f4aceb921cbf3d31a304fa89f51c77ea0)しました。

2019-05-30 12:28 UTC, korosuke613 commented on README.md
> +Added Example class.
[修正](https://github.com/KatLab-MiyazakiUniv/etrobocon2019/pull/45/commits/ab63b96f4aceb921cbf3d31a304fa89f51c77ea0)しました。

2019-05-30 12:29 UTC, korosuke613 commented on README.md
> +Create test cases for Example class.
[修正](https://github.com/KatLab-MiyazakiUniv/etrobocon2019/pull/45/commits/ab63b96f4aceb921cbf3d31a304fa89f51c77ea0)しました。

2019-05-30 12:29 UTC, korosuke613 commented on README.md
> +Add `ExampleTest.cpp` to `/test`.
[修正](https://github.com/KatLab-MiyazakiUniv/etrobocon2019/pull/45/commits/ab63b96f4aceb921cbf3d31a304fa89f51c77ea0)しました。

2019-05-30 12:29 UTC, korosuke613 commented on README.md
> +#### testing
[修正](https://github.com/KatLab-MiyazakiUniv/etrobocon2019/pull/45/commits/ab63b96f4aceb921cbf3d31a304fa89f51c77ea0)しました。

2019-05-30 12:29 UTC, Tamiyas commented on README.md
> +#### for example
なるほどね。OK

2019-05-30 12:30 UTC, korosuke613 commented on README.md
> +2. Put test code to `/test`.
[修正](https://github.com/KatLab-MiyazakiUniv/etrobocon2019/pull/45/commits/e58746215560f0cfb3faae1e3fd32aee3a30ff69)しました。

2019-05-30 12:32 UTC, shigyo123 commented on README.md
> +Normaly, please put to `/src/module`.
対象を明記してくれると助かります

2019-05-30 12:33 UTC, korosuke613 commented on README.md
> +Normaly, please put to `/src/module`.
[修正しました](https://github.com/KatLab-MiyazakiUniv/etrobocon2019/pull/45/commits/c8044ec9f3c72a295a87ef55df284cefabe63366)

2019-05-30 12:37 UTC, shigyo123 approved these changes

2019-05-30 12:44 UTC, Tamiyas approved these changes
チョーOK

2019-05-30 12:44 UTC, merged