Ticket 40
KatLab-MiyazakiUniv/etrobocon2019 pull request #53
Opened 2019-05-31 08:11 UTC by Tamiyas

### 変更点

### 実機テストの結果（実機テストが必要な場合）
 - 例: 10回走行させた平均値を書く
 - 例: 誤差率 [%] を書く
 - 例: 前回の手法との差を書く

#### 誤差率の計算式
誤差率 = （「測定値」 - 「理論値」） / 「理論値」 * 100

2019-05-31 08:12 UTC, korosuke613 commented
プルリクエスト名間違ってますよ

2019-05-31 08:15 UTC, korosuke613 reviewed
実数は、`double`じゃなくて`float`にしたんだったけ？

2019-05-31 08:18 UTC, korosuke613 commented on src/module/Pid.h
> +  float Kd_;  // Dゲイン
結局メンバ変数は`変数名`+`_`にする感じ？
それとも個人の自由？

2019-05-31 08:21 UTC, korosuke613 requested changes
CIによるテストが行われていません。
恐らく、宮地くんのリポジトリでCIの設定がされていないからかと思います。
設定してください。

2019-05-31 17:14 UTC, Tamiyas commented
CIの設定ってどうやるの？ 教えて！

2019-05-31 17:15 UTC, Tamiyas commented on src/module/Pid.h
> +  float Kd_;  // Dゲイン
僕がこうしてるだけ
強制するつもりもないよ
変えましょうか？

2019-06-01 06:34 UTC, sigenaga approved these changes

2019-06-01 13:49 UTC, korosuke613 commented on src/module/Pid.h
> +  float Kd_;  // Dゲイン
まあ、inじゃねーの！

2019-06-01 14:17 UTC, korosuke613 commented
@Tamiyas 
> CIの設定ってどうやるの？ 教えて！

[これ](https://github.com/KatLab-MiyazakiUniv/etrobocon2019/wiki/Fork%E5%85%88%E3%81%A7%E3%81%AECI%E8%A8%AD%E5%AE%9A%E6%96%B9%E6%B3%95)みて

2019-06-03 06:56 UTC, sigenaga approved these changes

2019-06-03 08:50 UTC, Tamiyas commented
> 実数は、`double`じゃなくて`float`にしたんだったけ？

@korosuke613 修正しましたよ

2019-06-03 09:12 UTC, korosuke613 approved these changes
`in jane-no!`

2019-06-03 09:13 UTC, merged