closed #38 Distanceクラスを作成
KatLab-MiyazakiUniv/etrobocon2019 pull request #55
Opened 2019-05-31 11:07 UTC by Oiwane

### 変更点
 - Distance.h、Distance.cpp、DistanceTest,cppの追加

### 実機テストの結果
 - テスト内容 : 10cm進んだら止める
 - 10回走行させた平均値 : 10.2125[cm]
 - 誤差率 2.125%
 - 停止時に機体がずれることがあり、それで誤差が発生している可能性あり

2019-05-31 11:32 UTC, sigenaga approved these changes
おっけーです。一つだけコメントしました。

2019-05-31 11:32 UTC, sigenaga commented on src/module/Distance.h
> +  double getDistance(Controller& controller);
&の前をスペースを空けるといいかもしれません

2019-05-31 11:35 UTC, Tamiyas requested changes
おそらくControllerを引数に持たせるのではなく
モーターの角度を引数にとった方がいい気がする

2019-05-31 11:35 UTC, Tamiyas commented on src/module/Distance.h
> +  double getDistance(Controller& controller);
Controllerを引数に取るのではなく、モーターの角度を引数に取ったほうがいい気がする

2019-05-31 12:04 UTC, Oiwane commented on src/module/Distance.h
> +  double getDistance(Controller& controller);
引数を変更したので、&は消えました

2019-05-31 12:04 UTC, Oiwane commented on src/module/Distance.h
> +  double getDistance(Controller& controller);
変更しました

2019-06-01 14:23 UTC, korosuke613 commented
@Oiwane 
[これ](https://github.com/KatLab-MiyazakiUniv/etrobocon2019/wiki/Fork%E5%85%88%E3%81%A7%E3%81%AECI%E8%A8%AD%E5%AE%9A%E6%96%B9%E6%B3%95)みてCIの設定をしてね

2019-06-02 03:39 UTC, Oiwane commented
@korosuke613 
恐らく設定できたと思います。
CircleCIはfork先のmasterブランチを見ているのでしょうか？

2019-06-02 08:02 UTC, korosuke613 commented
> @korosuke613
> 恐らく設定できたと思います。
> CircleCIはfork先のmasterブランチを見ているのでしょうか？

@Oiwane 
再プッシュしたらできたね
Good Job!

2019-06-02 08:26 UTC, Tamiyas approved these changes
OK! 精度はこれから良くしていこう！

2019-06-02 08:27 UTC, merged

2019-06-03 10:02 UTC, Morichan commented on src/module/Distance.cpp
> + * @return 走行距離
今更ながら横から失礼します！（詳細はM2の誰かから聞いてください）

できれば単位が欲しいです。
メートルなのかミリメートルなのかで、メソッド利用者の使い方も変わると思います。

ついでに、引数の方にも単位を追加しておくといいと思います。

2019-06-04 01:35 UTC, Oiwane commented on src/module/Distance.cpp
> + * @return 走行距離
[こちら](https://github.com/KatLab-MiyazakiUniv/etrobocon2019/pull/59)で変更しました