[WIP]closed #33
KatLab-MiyazakiUniv/etrobocon2019 pull request #57
Opened 2019-06-02 18:22 UTC by korosuke613

### 変更点
キャリブレーションを行うためのクラス(Calibrator)を追加。

### 実機テストの結果（実機テストが必要な場合）
Work in progress.

#### 誤差率の計算式
誤差率 = （「測定値」 - 「理論値」） / 「理論値」 * 100

2019-06-03 06:54 UTC, sigenaga requested changes

2019-06-03 06:54 UTC, sigenaga commented on .vscode/launch.json
> +    // IntelliSense を使用して利用可能な属性を学べます。
赤くなっているけど、大丈夫なんですか？

2019-06-03 06:54 UTC, sigenaga commented on src/module/Calibrator.cpp
> +  while (!con.buttonIsPressedEnter()) {
（））となってますが大丈夫でしょうか。

2019-06-03 06:54 UTC, sigenaga commented on src/module/Calibrator.cpp
> +  int tmp_color = 0;
キャメルケースにしないとダメだと思います。間違っていたらすみません。

2019-06-03 06:54 UTC, sigenaga commented on src/module/Calibrator.cpp
> +  int mean_brightness = 0;
キャメルケースじゃないとダメだと思います。間違っていたらすみません。

2019-06-03 07:31 UTC, korosuke613 commented on src/module/Calibrator.cpp
> +  while (!con.buttonIsPressedEnter()) {
```
while(
  ! con. buttonIsPressedEnter()
)
```
だから大丈夫！
whileの括弧の中に`buttonIsPressedEnter`メソッドの括弧があるって感じやね

2019-06-03 07:33 UTC, korosuke613 commented on .vscode/launch.json
> +    // IntelliSense を使用して利用可能な属性を学べます。
このファイルはVSCodeの設定ファイルなんだけど、
赤くなっている理由は、JSONにコメントの概念がないからやね。

でも、VSCode的には大丈夫。VSCode側が`//`は無視してくれるから

2019-06-03 07:41 UTC, sigenaga commented on .vscode/launch.json
> +    // IntelliSense を使用して利用可能な属性を学べます。
なるほど・・。奥が深いですね

2019-06-03 07:42 UTC, sigenaga approved these changes

2019-06-03 08:34 UTC, korosuke613 commented on src/module/Calibrator.cpp
> +  int tmp_color = 0;
THX !!!!

[修正](https://github.com/KatLab-MiyazakiUniv/etrobocon2019/pull/57/commits/166ee209f357e4f2f33ad1109efd65eaadeb192c)した！

2019-06-03 08:34 UTC, korosuke613 commented on src/module/Calibrator.cpp
> +  int mean_brightness = 0;
THX !!!!

[修正](https://github.com/KatLab-MiyazakiUniv/etrobocon2019/pull/57/commits/166ee209f357e4f2f33ad1109efd65eaadeb192c)した！

2019-06-03 10:05 UTC, Tamiyas requested changes
だめだめだめだめだめ

2019-06-03 10:05 UTC, Tamiyas commented on .gitignore
> +a.out
これは、実行ファイルじゃねえのかい？
下の「#実行ファイル」の欄に書けばいいじゃん

2019-06-03 10:05 UTC, Tamiyas commented on src/module/Calibrator.h
> +  Controller& con;
conって何だよ
controllerに名前を変えて

2019-06-03 10:05 UTC, Tamiyas commented on src/module/Calibrator.h
> +  bool isFinish =
コンストラクタで初期化して
他のメンバー変数も！

2019-06-03 10:05 UTC, Tamiyas commented on src/module/Calibrator.cpp
> +  isFinish = setLRCource();
calibrationが正常終了したかどうかを戻り値として返したいのならば、
毎回のset処理の後に条件分岐が必要

2019-06-03 10:05 UTC, Tamiyas commented on src/module/Calibrator.cpp
> +bool Calibrator::setBrightness(Brightness b) {
変数bって何だよ
brightNessとかにしてよ

2019-06-03 10:05 UTC, Tamiyas commented on src/module/Calibrator.cpp
> +    tmpColor = con.getBrightness();
ここでtmpColorを宣言すればいいんじゃない？

2019-06-03 10:05 UTC, Tamiyas commented on src/module/Calibrator.cpp
> +  int meanBrightness = 0;
ここに以下の処理を記述したコメントがあるといいかもですねぇ

2019-06-03 11:07 UTC, Morichan reviewed
疑問をいくつか（下の段落を含め4つ）投げました。
間違ってるところがあれば教えてください。

setLRCourse()とsetBrightness()で思ったことについても書きます。
set〜という関数名にしては重くないですか？
別の関数名の方がいいと思うのですが。

2019-06-03 11:07 UTC, Morichan commented on .vscode/launch.json
> +    // IntelliSense を使用して利用可能な属性を学べます。
VS Codeを使ってない人はこのファイルをそのまま使えないってことですか？
それは問題ではないということ？

2019-06-03 11:07 UTC, Morichan commented on src/module/Calibrator.cpp
> +bool Calibrator::calibration() {
戻り値がboolだけど、メンバ関数名はこれでいいんですか？
しかも返してるのがisFinishで中身はsetLRCourse()の戻り値ってのは、名前と処理内容が合ってないように感じます

この戻り値はあくまでキャリブレーションの成功不成功を表す真偽値で、呼出側がそれに応じて処理を変えなければならないのであれば、コメントにその旨を記載すべきだと思います。
特にfalseが帰ってきたときは、これこれをしてくださいと参考コードまであると親切ですね。

あと、他で使ってないのであれば、setLRCourse()はプライベートにしてもいいのでは？

2019-06-03 11:07 UTC, Morichan commented on src/module/Calibrator.cpp
> +  if(b == Brightness::WHITE){
if文のカッコの位置など、統一が取れていないように見えます。
特に決まってないのですか？

2019-06-03 11:11 UTC, korosuke613 commented on .gitignore
> +a.out
[fix](https://github.com/KatLab-MiyazakiUniv/etrobocon2019/pull/57/commits/d6d268d9ffe4b7b7b9473e69b1e12d3b2b4c82cc)

2019-06-03 11:14 UTC, korosuke613 commented on src/module/Calibrator.h
> +  Controller& con;
[fix](https://github.com/KatLab-MiyazakiUniv/etrobocon2019/pull/57/commits/2d8f968173cc4352cfc652507e750397dc1c148c)

2019-06-03 11:26 UTC, korosuke613 commented on src/module/Calibrator.h
> +  bool isFinish =
[fix](https://github.com/KatLab-MiyazakiUniv/etrobocon2019/pull/57/commits/cd5cd873d3bd034b0d784a0e8cea890a55921142)

2019-06-04 08:33 UTC, korosuke613 commented on src/module/Calibrator.cpp
> +  isFinish = setLRCource();
[fix](https://github.com/KatLab-MiyazakiUniv/etrobocon2019/pull/57/commits/8d2c64bc008b90458b91c8c3b6da9805ee8af315)

2019-06-04 08:34 UTC, korosuke613 commented on src/module/Calibrator.cpp
> +bool Calibrator::setBrightness(Brightness b) {
[fix](https://github.com/KatLab-MiyazakiUniv/etrobocon2019/pull/57/commits/8672c76be7232d6bc606b6b05cf4144611c92b9a)

2019-06-04 08:35 UTC, korosuke613 commented on src/module/Calibrator.cpp
> +    tmpColor = con.getBrightness();
[fix](https://github.com/KatLab-MiyazakiUniv/etrobocon2019/pull/57/commits/32d0e89fad134011b6c47e4b5c3aa4a877d453e3)

2019-06-04 08:36 UTC, korosuke613 commented on src/module/Calibrator.cpp
> +  int meanBrightness = 0;
[fix](https://github.com/KatLab-MiyazakiUniv/etrobocon2019/pull/57/commits/9f4858897cc43198f9140c1fcf0e0c12c3e3bb99)

2019-06-04 08:45 UTC, korosuke613 commented on src/module/Calibrator.cpp
> +bool Calibrator::calibration() {
> 戻り値がboolだけど、メンバ関数名はこれでいいんですか？

メンバ関数名はこちらで構いません。

> しかも返してるのがisFinishで中身はsetLRCourse()の戻り値ってのは、名前と処理内容が合ってないように感じます

修正しました。

> この戻り値はあくまでキャリブレーションの成功不成功を表す真偽値で、呼出側がそれに応じて処理を変えなければならないのであれば、コメントにその旨を記載すべきだと思います。

ヘッダファイルにコメントしています。

> 特にfalseが帰ってきたときは、これこれをしてくださいと参考コードまであると親切ですね。

コードは書いてませんが、対処すべきことを書きました。

> あと、他で使ってないのであれば、setLRCourse()はプライベートにしてもいいのでは？

 テストで使っています。

2019-06-04 08:46 UTC, korosuke613 commented on src/module/Calibrator.cpp
> +  if(b == Brightness::WHITE){
フォーマットしました。

2019-06-05 05:45 UTC, Tamiyas reviewed
おおむね、良いと思います

2019-06-05 05:45 UTC, Tamiyas commented on src/module/Calibrator.cpp
> +int Calibrator::meaningBrightness(){
算術平均を表現する場合は、averageよりもmeanの方が適切な気がするけど
meanには「平均をとる」っていう意味はないはず
ここは、「averageBrightness」の方が関数名としてふさわしい...と思う。

2019-06-05 05:45 UTC, Tamiyas commented on src/module/Calibrator.cpp
> +int Calibrator::getWhiteBrightness() { return brightnessOfWhite; };
細かいことだけど、メンバー変数に変更を加えない関数の場合は「関数にconstをつける」方がいいよ。
`int Calibrator::getWhiteBrightness() const { return brightnessOfWhite; };` のように

2019-06-06 04:30 UTC, korosuke613 commented on src/module/Calibrator.cpp
> +int Calibrator::meaningBrightness(){
[fix](https://github.com/KatLab-MiyazakiUniv/etrobocon2019/pull/57/commits/9b3ac9755d7f07ff0930f53b846df46f09da1d2b)

2019-06-06 04:30 UTC, korosuke613 commented on src/module/Calibrator.cpp
> +int Calibrator::getWhiteBrightness() { return brightnessOfWhite; };
[はえー知らんかった。](https://github.com/KatLab-MiyazakiUniv/etrobocon2019/pull/57/commits/2b8d0c6b6d2cd118af16a143a41f7f4937b6222d)

2019-06-06 05:04 UTC, Tamiyas approved these changes
言い残すことはない

2019-06-06 06:09 UTC, merged