Closed #39 ライントレーサークラス(LineTracer)の作成
KatLab-MiyazakiUniv/etrobocon2019 pull request #69
Opened 2019-06-07 11:21 UTC by Takahiro55555

### 変更点
LineTracer.cpp、LineTracer.h、LineTracerTest.cpp、SpeedControl.cpp（ダミー）、SpeedControl.h（ダミー）を追加しました。

### 実機テストの結果
走行テストを行い、走行することができました。
なお、パラメータの値は適当に設定しました。
[Googleフォト](https://photos.app.goo.gl/9ZPo6S7uPn7JEgEeA)

2019-06-08 05:20 UTC, sigenaga approved these changes

2019-06-08 07:59 UTC, Takahiro55555 commented
### 変更点
旋回処理が左右逆だったため修正しました。

### 実機テストに関して
目標走行距離と実際の走行距離にずれが無いか確かめ、ずれが無いことを確認しました。

走行動画\
[走行距離の確認](https://photos.app.goo.gl/X8vNa1qyLVd46xK27)\
[Rコース走行](https://photos.app.goo.gl/JrkL7zWK5887Apdu8)\
[Lコース走行](https://photos.app.goo.gl/GNMsQTxAro25JW61A)

#### 走行距離の確認（目標走行距離：1000mm）
目標距離と実際の走行距離にずれが無いか確かめた際の `EtRobocon2019.cpp` のコードです。

```c++
void EtRobocon2019::start() {
    Controller controller;
    Calibrator calibrator(controller);

    calibrator.calibration();

    //右ボタンが押されるまで待つ
    while (!controller.buttonIsPressedRight())
    {}

    //コースと、カラーセンサー目標値の設定
    bool isRightCourse = !calibrator.isLeftCource();
    int targetBrightness = (calibrator.getWhiteBrightness() + calibrator.getBlackBrightness()) / 2;
    LineTracer lineTracer(targetBrightness, isRightCourse);

    controller.speakerPlayToneFS6(200);

    // 1000mm 走行する
    NormalCourceProperty settings = {1000, 30, {0.1, 0.0, 0.0}, {0.1, 0.0, 0.0}};
    lineTracer.run(settings);
    
    controller.speakerPlayToneFS6(300);
}
```

#### カーブも含めたライントレース時
ライントレースさせた際の `EtRobocon2019.cpp` のコードです。

```c++
void EtRobocon2019::start() {
    Controller controller;
    Calibrator calibrator(controller);

    calibrator.calibration();

    // 右ボタンが押されるまで待つ    
    while (!controller.buttonIsPressedRight())
    {}

    // コースと、カラーセンサー目標値の設定
    bool isRightCourse = !calibrator.isLeftCource();
    int targetBrightness = (calibrator.getWhiteBrightness() + calibrator.getBlackBrightness()) / 2;
    LineTracer lineTracer(targetBrightness, isRightCourse);

    // 最初の直線コース
    controller.speakerPlayToneFS6(200);
    NormalCourceProperty settings = {650, 30, {0.1, 0.0, 0.0}, {0.1, 0.01, 0.0}};
    lineTracer.run(settings);

    // 最初のカーブ
    controller.speakerPlayToneFS6(100);
    lineTracer.setTargetBrightness(targetBrightness + targetBrightness/2);
    settings = {700, 30, {0.1, 0.0, 0.0}, {0.4, 0.001, 0.0}};
    lineTracer.run(settings);

    // ２番目の直線コース（コースアウト）
    controller.speakerPlayToneFS6(100);
    lineTracer.setTargetBrightness(targetBrightness);
    settings = {600, 30, {0.1, 0.0, 0.0}, {0.12, 0.01, 0.0}};
    lineTracer.run(settings);

    // 2番目のカーブ（コースアウト）
    controller.speakerPlayToneFS6(100);
    settings = {800, 30, {0.1, 0.0, 0.0}, {0.35, 0.01, 0.0}};
    lineTracer.run(settings);

    controller.speakerPlayToneFS6(300);
}
```

2019-06-10 01:21 UTC, sigenaga approved these changes

2019-06-10 01:21 UTC, sigenaga commented on src/module/LineTracer.h
> +    void run(NormalCourceProperty &settings);
normalじゃなくて、Normalになってますけど大丈夫でしょうか？

2019-06-10 01:54 UTC, arimakaoru commented
NormalCour**c**ePropertyは、NormalCour**s**ePropertyのスペルミスですか？

2019-06-10 04:03 UTC, Tatsumi0000 commented on src/module/LineTracer.h
> +    void run(NormalCourceProperty &settings);
50行目の
`void run(NormalCourceProperty &settings);`
が
`void run(normalCourceProperty &settings);`じゃないかってこと？

2019-06-10 04:25 UTC, Tamiyas requested changes
概ね、良いと思います。
ソースコードの少ーし気になる点をいくつか書きました。

ところで、コーディング規約が適用されていないようです。clang-formatの設定はできていますか？

2019-06-10 04:25 UTC, Tamiyas commented on src/module/LineTracer.h
> +#include "SpeedControl.h"
ごめん、僕のせいだ
`SpeedControl.h`と`TurnControl.h`の模擬コードのファイルをコミットしていないからビルドが通らないんだね。
上記2つをコミット対象とすれば、リンカーが動いてくれると思うけど、どうしよう

2019-06-10 04:25 UTC, Tamiyas commented on src/module/LineTracer.h
> +struct PidParameter
将来的な話になるけど、`SpeedControl.h`または`TurnControl.h`が`Pid.h`をインクルードすれば
`PidGain`構造体(`Pid.h`にある)が使えるようになるから`PidParameter`構造体は要らなくなるね。

2019-06-10 04:25 UTC, Tamiyas commented on test/LineTracerTest.cpp
> +    struct NormalCourceProperty settings =
好みだけど、C++では`struct`キーワードを付けなくてもいいよ
C言語では`typedef`しないと`struct`キーワードは省略できなかったけどね。

2019-06-10 04:25 UTC, Tamiyas commented on src/module/LineTracer.cpp
> +    int turnValue;                         // 旋回値
初期化してほしいですね。
それか、`while`ループの中で毎回変数を作成するのもいいですね。

2019-06-10 04:25 UTC, Tamiyas commented on src/module/LineTracer.cpp
> +LineTracer::LineTracer(int targetBrightness_, bool isRightCourse_)
ここは、`isRightCourse`ではなく`isLeftCourse`の方がいいですね。

`Calibrator`クラスに`isLeft`という変数があるので。

2019-06-10 22:29 UTC, sigenaga approved these changes

2019-06-11 04:25 UTC, Takahiro55555 commented on src/module/LineTracer.h
> +    void run(NormalCourceProperty &settings);
スペルミスがあったため`void run(NormalCourseProperty &settings);`に修正しました。

2019-06-11 09:03 UTC, Tamiyas approved these changes
OKだと思います

2019-06-11 09:05 UTC, merged