closed #47 前進値の制御クラス作成
KatLab-MiyazakiUniv/etrobocon2019 pull request #70
Opened 2019-06-09 07:25 UTC by match97

### 変更点
speedControl.cpp, speedControlTest.cpp, speedControl.hの追加

2019-06-10 01:17 UTC, sigenaga approved these changes
個人的にはコメントとその役割を１セットにして、スペースを空けたほうが見やすいです

2019-06-10 03:48 UTC, Tamiyas requested changes
いろいろ分からないところがあるので、質問しました。
すみませんが、replyしてくれると助かります。

あと、コーディング規約が適用されていないようです。clang-formatの設定はできていますか？

2019-06-10 03:48 UTC, Tamiyas commented on src/module/SpeedControl.cpp
> + *  @param  targetSpeed [目標の速度]
単位があると嬉しいですね。

2019-06-10 03:48 UTC, Tamiyas commented on src/module/SpeedControl.cpp
> +    currentSpeed = distance / delta;
distanceの戻り値は、開始点から現在までの走行距離なので
deltaは0.004ではなく、開始点から現在までの時間でなければいけないと思います。

2019-06-10 03:48 UTC, Tamiyas commented on src/module/SpeedControl.cpp
> +    controller.leftWheel.setPWM(pidSpeed);
`SpeedControl`はモーターを回す処理もするのですね。
旋回値制御クラスでは`setPWM()`は呼び出さず、PID制御して求めたPWM値を返すだけでしたが
問題ありませんか？

2019-06-10 03:48 UTC, Tamiyas commented on src/module/SpeedControl.cpp
> +    currentSpeed = currentSpeed + 2 * distance / delta + currentSpeed;
すみません、この処理が何をやっているか分かりません。
教えてください。

2019-06-10 03:48 UTC, Tamiyas commented on test/SpeedControlTest.cpp
> +TEST(SpeedControl, SpeedControl_inti)
`SpeedControl_init`ですか？

2019-06-10 04:16 UTC, Tatsumi0000 commented
clang-formatの設定方法は，
https://github.com/KatLab-MiyazakiUniv/etrobocon2019/wiki/VSCode%E3%81%A7clang-format%E3%81%AE%E8%A8%AD%E5%AE%9A
↑見ればいいと思います．
ただし，この設定はプロジェクト内にclang-formatファイルを入れないといけない．

2019-06-10 05:46 UTC, match97 commented on test/SpeedControlTest.cpp
> +TEST(SpeedControl, SpeedControl_inti)
`SpeedControl_init`です。訂正しました。

2019-06-10 07:07 UTC, match97 commented
大幅修正しました。
もう一度レビューお願い致します。

2019-06-10 07:30 UTC, Tamiyas commented on src/module/SpeedControl.h
> +    const double C;   //定数C(実験で求める予定)
できれば、実験してからプルリク送ってほしいです

2019-06-10 07:40 UTC, Tamiyas reviewed
すみませんが、定数 `C` を実験で求めてからプルリクを送ってほしいです。

2019-06-10 07:40 UTC, Tamiyas commented on src/module/SpeedControl.cpp
> +    controller.tslpTsk(4);
`tslpTsk`を呼び出すのではなく、`prevDistance`をメンバー変数にもたせるように変更した方が
何かと安心な気がします

2019-06-10 07:40 UTC, Tamiyas commented on src/module/SpeedControl.cpp
> +    double PWMValue = pidValue * 360 / (M_PI * radius * C);
コーディング規約的には`PWMValue`ではなく`pwmValue`だと思います

2019-06-10 08:21 UTC, match97 commented on src/module/SpeedControl.cpp
> +    controller.tslpTsk(4);
コンストラクタで`prevDistance`を求めるということですか？
もしそうならば、`prevDistance`から`nextDistance`までの間の時間が分からないため`curentSpeed`が求められないと思います。

2019-06-10 08:37 UTC, Tamiyas commented on src/module/SpeedControl.cpp
> +    controller.tslpTsk(4);
時間は4msecじゃないの？
コンストラクターでは、SpeedControlクラスを作成した時点の走行体の距離を`prevDistance`に代入するだけでいいと思うよ。
そして`calculateSpeed`を呼び出したときの走行体の距離と`prevDistance`を引き算することによって4msecで移動した走行体の距離が出せるよね

2019-06-10 22:30 UTC, sigenaga approved these changes

2019-06-11 05:42 UTC, Tamiyas requested changes
いくつか気になる点がありました。修正お願いします。

2019-06-11 05:42 UTC, Tamiyas commented on src/module/SpeedControl.cpp
> +SpeedControl::SpeedControl() : C(7.2), radius(50) {
` : dist(), controller(), C(7.2), radius(50) { ... `
に変更してください

2019-06-11 05:42 UTC, Tamiyas commented on src/module/SpeedControl.cpp
> +  Distance dist;
これ要る？

2019-06-11 05:42 UTC, Tamiyas commented on src/module/SpeedControl.cpp
> +  Controller controller;
これ要る？

2019-06-11 09:01 UTC, Tamiyas approved these changes
OKだと思います

2019-06-11 09:01 UTC, merged