closed#41 Navigatorクラスの作成
KatLab-MiyazakiUniv/etrobocon2019 pull request #71
Opened 2019-06-11 03:33 UTC by harakai

### 変更点
Navigator.cppとNavigator.hを追加

### 実機テストの結果（実機テストが必要な場合）
 - PWM値30で10回前方に10cm走行させた平均値 : 10.3cm
 - PWM値30で10回後方に10cm走行させた平均値 : 11.57cm
 - 前者の誤差率 [3%]
 - 後者の誤差率 [15.7%]

### 考察
 - 後者の方は急発進による前傾姿勢の状態で走行したため、停止をした際に大きく後退していた
 - ※試しにPWM値を10に変更して一回後方に10cm走行させたところ、ほぼ10cm進んで停止した

2019-06-11 06:21 UTC, sigenaga approved these changes

2019-06-11 06:27 UTC, korosuke613 commented
@harakai 
fork先でCIが設定されていないみたいだね。
[ここ](https://github.com/KatLab-MiyazakiUniv/etrobocon2019/wiki/Fork%E5%85%88%E3%81%A7%E3%81%AECI%E8%A8%AD%E5%AE%9A%E6%96%B9%E6%B3%95)を参照して設定して〜

2019-06-11 06:27 UTC, korosuke613 requested changes
テストが実行されていません。

2019-06-11 08:00 UTC, harakai commented
> テストが実行されていません。

先ほど終わりました。
すみませんでした。

2019-06-11 08:08 UTC, korosuke613 requested changes
変更してください。

2019-06-11 08:08 UTC, korosuke613 commented on src/module/Navigator.cpp
> +    : distance(), controller()
引数無しのコンストラクタは使うことないと思うから、必要ないなら消してください。

2019-06-11 08:08 UTC, korosuke613 commented on src/module/Navigator.h
> +   Navigator();
引数無しのコンストラクタは使うことがないと思うから、必要ないなら消してください。

2019-06-11 08:08 UTC, korosuke613 commented on src/module/Navigator.h
> +   Navigator(Controller &_controller);
もし、コンストラクタがこれ１つになるなら、

```c++
explicit Navigator(Controller &_controller);
```

にしてください。

2019-06-11 08:08 UTC, korosuke613 commented on src/module/Navigator.cpp
> +    : distance(), controller(_controller)
仮引数`_controller`は`controller_`に名前を改めてください。

2019-06-11 08:08 UTC, korosuke613 commented on src/module/Navigator.h
> +   Navigator(Controller &_controller);
仮引数`_controller`は`controller_`に名前を改めてください。

2019-06-11 08:08 UTC, korosuke613 commented on src/module/Navigator.cpp
> +
`Navigator::forward`と`Navigator::back`は共通の処理が多いから、共通の処理はメソッドに切り分けられる気もするけど...
どうだろうか @Tamiyas

2019-06-11 08:19 UTC, Tamiyas commented on src/module/Navigator.cpp
> +
`Navigator::forward`と`Navigator::back`を共通するのではなく、
それぞれに含まれる共通部分を別の関数として1つにまとめようということ？

それなら賛成！

2019-06-11 08:24 UTC, korosuke613 commented on src/module/Navigator.cpp
> +
Exactory(その通りでございます).

2019-06-11 09:08 UTC, korosuke613 commented on src/Makefile.inc
> +    Navigator.o
```
Navigator.o \
```
にしてください。（ごめんなさい）

2019-06-12 03:01 UTC, Tamiyas reviewed
少ーし気になる点を書きました。

2019-06-12 03:01 UTC, Tamiyas commented on src/module/Navigator.cpp
> +void Navigator::move(int specifiedValue, int pwm)
引数名`specifiedValue`は、ちょっと不親切じゃない？
せめて、使用方法を明記したコメントがあれば分かるけど
あと単位もほしいな

2019-06-12 03:01 UTC, Tamiyas commented on src/module/Navigator.h
> +   void back(int specifiedValue, int pwm);
`forward`とくれば`backward`かな？

2019-06-12 03:01 UTC, Tamiyas commented on src/module/Navigator.h
> +#ifndef Navigator_H
特に制約を付けていたわけではないのだけど
インクルードガードのマクロ定数は、識別子名との衝突を避ける目的で、基本すべて大文字にする慣習があるので`#ifndef NAVIGATOR_H`の方が自然
「こうするんです！」という強い思いがあるなら直さなくてもいいです。

2019-06-12 03:10 UTC, korosuke613 requested changes

2019-06-12 03:10 UTC, korosuke613 commented on src/module/Navigator.h
> +   Controller controller;
Controllerはコンストラクタで参照渡ししているので、ここでは、

Controller & controller

と言うふうにしてください

2019-06-12 11:49 UTC, closed without merging