Ticket 35
KatLab-MiyazakiUniv/etrobocon2019 pull request #83
Opened 2019-06-12 10:53 UTC by Tatsumi0000

### 変更点
- 構造体（の配列）に設定したパラメータに応じてNormalCourseを走る．
- 構造体の配列を１つずつパラメータをLineTracerクラスのrunメソッドに渡す．
- １つの区間が終わるとブザーを鳴らす．

### 実機テストの結果（実機テストが必要な場合）
 - 実際にライントレースして走る．（パラメーターをある程度しか設定していないので途中でコースアウトする）

2019-06-13 07:27 UTC, arimakaoru commented on src/module/NormalCourse.h
> +  bool selectedEdge;
左エッジ＝左コースならば、
`selectedEdge`よりも`isLeftCourse`とかにしてはどうでしょうか？

`isLeftCourse`の方が、この変数はbool型であり、trueは左コースを表すことがわかりやすいと思いました...

2019-06-13 10:33 UTC, korosuke613 requested changes
質問に答えて〜

2019-06-13 10:33 UTC, korosuke613 commented on src/module/NormalCourse.cpp
> +  NormalCourse::runNormalCourse();
runNormalCourse()をやる必要はあるの？
エッジ切り替えだけじゃないのけ？

2019-06-13 10:33 UTC, korosuke613 commented on src/module/NormalCourse.cpp
> +      = { { { 1000, 10, speedPid[0], turnPid[0] }, { 500, 80, speedPid[1], turnPid[1] } } };
なんか...汚い気がする
それぞれの区間のパラメータ設定ってもっときれいにする方法ないかな？
normalCourseProperty ` { 1000, 10, speedPid[0], turnPid[0] }`とspeedPid `{ 0.1, 0.0, 0.0 }`とturnPid `{ 0.1, 0.0, 0.0 }`が離れているのが気に入らない。

2019-06-13 12:29 UTC, Tatsumi0000 commented on src/module/NormalCourse.h
> +  bool selectedEdge;
確かに．`isLeftCourse`に変更します．

2019-06-13 12:32 UTC, Tatsumi0000 commented on src/module/NormalCourse.cpp
> +  NormalCourse::runNormalCourse();
確かに．
やる必要なしだね．ETrobocon2019で普通に呼び出せばいいね．

2019-06-13 12:47 UTC, Tatsumi0000 commented on src/module/NormalCourse.cpp
> +      = { { { 1000, 10, speedPid[0], turnPid[0] }, { 500, 80, speedPid[1], turnPid[1] } } };
今思いついたのは，
```cpp

std::array<NormalCourseProperty, arraySize> normalCourseProperty
      = { { { 1000, 10, { 0.1, 0.0, 0.0 }, { 0.1, 0.01, 0.0 } },
            { 500, 80, { 0.1, 0.0, 0.0 }, { 0.1, 0.01, 0.0 } } } };
  LineTracer lineTracer(targetBrightness, selectedEdge);
  for(auto& ncp : normalCourseProperty) {
    lineTracer.run(ncp);
    // １区間終わるごとに音を奏でる．
    controller.speakerPlayToneFS6(100);
  }
```

か，

```cpp
LineTracer lineTracer(targetBrightness, selectedEdge);
// 第1区間
NormalCourceProperty settings = {650, 30, {0.1, 0.0, 0.0}, {0.1, 0.01, 0.0}};
lineTracer.run(settings);

// 第2区間
settings = {700, 30, {0.1, 0.0, 0.0}, {0.4, 0.001, 0.0}};
lineTracer.run(settings);
```
みたいな感じでずっと書いていくかだと思うのですが，代替案ありますか？

2019-06-13 13:08 UTC, korosuke613 commented on src/module/NormalCourse.cpp
> +      = { { { 1000, 10, speedPid[0], turnPid[0] }, { 500, 80, speedPid[1], turnPid[1] } } };
うわーこれは迷いますな

2019-06-13 13:08 UTC, korosuke613 commented on src/module/NormalCourse.cpp
> +      = { { { 1000, 10, speedPid[0], turnPid[0] }, { 500, 80, speedPid[1], turnPid[1] } } };
とりあえずどっちかで良いと思います！

2019-06-13 13:11 UTC, Tatsumi0000 commented on src/module/NormalCourse.cpp
> +      = { { { 1000, 10, speedPid[0], turnPid[0] }, { 500, 80, speedPid[1], turnPid[1] } } };
それか，ノーマルコースを走らせる人がここは，好きに書いてもらうか（ここは，ライントレースのパラメータの設定方法だけでもわかればいいなと思っているので）．

2019-06-13 13:15 UTC, Tatsumi0000 commented on src/module/NormalCourse.cpp
> +      = { { { 1000, 10, speedPid[0], turnPid[0] }, { 500, 80, speedPid[1], turnPid[1] } } };
とりあえずは，
```cpp
std::array<NormalCourseProperty, arraySize> normalCourseProperty
      = { { { 1000, 10, { 0.1, 0.0, 0.0 }, { 0.1, 0.01, 0.0 } },
            { 500, 80, { 0.1, 0.0, 0.0 }, { 0.1, 0.01, 0.0 } } } };
  LineTracer lineTracer(targetBrightness, selectedEdge);
  for(auto& ncp : normalCourseProperty) {
    lineTracer.run(ncp);
    // １区間終わるごとに音を奏でる．
    controller.speakerPlayToneFS6(100);
  }
```
こっちにしておきます！

2019-06-13 17:15 UTC, korosuke613 approved these changes
いいと思います

2019-06-14 06:00 UTC, arimakaoru approved these changes
良いと思います！

2019-06-14 18:05 UTC, merged