closed#41 Navigatorクラスの作成
KatLab-MiyazakiUniv/etrobocon2019 pull request #84
Opened 2019-06-12 12:02 UTC by harakai

### 変更点
Navigator.cppとNavigator.hを追加
### 実機テストの結果（実機テストが必要な場合）
 - PWM値30で10回前方に10cm走行させた平均値 : 10.3cm
 - PWM値30で10回後方に10cm走行させた平均値 : 11.57cm
 - 前者の誤差率 [3%]
 - 後者の誤差率 [15.7%]

#### 考察
 - 後者の方は急発進による前傾姿勢の状態で走行したため、停止をした際に大きく後退していた
 - ※試しにPWM値を10に変更して一回後方に10cm走行させたところ、ほぼ10cm進んで停止した

2019-06-13 02:23 UTC, arimakaoru commented on src/module/Navigator.cpp
> +    result = distance.getDistance(leftAngle, rightAngle) <= goalDistance
セミコロンを付け忘れていませんか？

2019-06-13 03:03 UTC, arimakaoru requested changes
ちょっと細かいところが気になってしまいました。

2019-06-13 03:03 UTC, arimakaoru commented on src/module/Navigator.cpp
> +    result = distance.getDistance(leftAngle, rightAngle) >= goalDistance
セミコロンを付け忘れていませんか？

2019-06-13 03:03 UTC, arimakaoru commented on test/NavigatorTest.cpp
> +  navigator.move(1000);
`navigator.move(1000);`の前後で`getDistance`を呼び出して、その戻り値を`ASSERT_DOUBLE_EQ`で比較してはどうでしょうか。

2019-06-13 03:03 UTC, arimakaoru commented on test/NavigatorTest.cpp
> +  navigator.move(1000, 50);
`navigator.move(1000, 50);`の前後で`getDistance`を呼び出して、その戻り値を`ASSERT_DOUBLE_EQ`で比較してはどうでしょうか。

2019-06-13 03:03 UTC, arimakaoru commented on test/NavigatorTest.cpp
> +  navigator.move(-1000);
`navigator.move(-1000);`の前後で`getDistance`を呼び出して、その戻り値を`ASSERT_DOUBLE_EQ`で比較してはどうでしょうか。

2019-06-13 03:03 UTC, arimakaoru commented on test/NavigatorTest.cpp
> +  navigator.move(-1000, 50);
`navigator.move(-1000, 50);`の前後で`getDistance`を呼び出して、その戻り値を`ASSERT_DOUBLE_EQ`で比較してはどうでしょうか。

2019-06-13 03:03 UTC, arimakaoru commented on src/module/Navigator.cpp
> +  else{
else
    {

clang-format効いてますか？

2019-06-13 03:12 UTC, arimakaoru commented on src/module/Navigator.cpp
> +    : distance(), controller(controller_)
@Tamiyas 
`distance()`は、カッコの中が空の場合でも必要ですか？

2019-06-13 09:06 UTC, Tamiyas commented on src/module/Navigator.cpp
> +    : distance(), controller(controller_)
@arimakaoru 
必要ですね
確かに、クラスDistanceのコンストラクタは引数をとらないので、初期化するものがdistanceだけなら必要ありません
しかし今回の場合は、クラスNavigatorの引数が複数あるので、初期化する順番が変わらないように明示してあげる必要があります

2019-06-13 09:53 UTC, Oiwane reviewed
一緒にコーディングしていて気付かなかった点を挙げました

2019-06-13 09:53 UTC, Oiwane commented on src/module/Navigator.cpp
> +  int goalDistance = specifiedValue + distance.getDistance(leftAngle, rightAngle);
`distance.getDistance(leftAngle, rightAngle)`の戻り値はdoubleなのでキャストして使用してください

2019-06-13 09:53 UTC, Oiwane commented on src/module/Navigator.cpp
> + * @brief モータを動かし、isMovedを満たす間動く
`isMovedを満たす間`は曖昧で意味が伝わりづらい気がします
`isMovedメソッドの戻り値がtrueの間`とかはどうでしょう

あと`forward`と`backward`のbriefが全く同じなので
`動く`を`前進する`と`後進する`にそれぞれ変更したほうがいい気がします

2019-06-13 09:53 UTC, Oiwane commented on src/module/Navigator.cpp
> + * @brief モータを動かし、isMovedを満たす間動く
`isMovedを満たす間`は曖昧で意味が伝わりづらい気がします
`isMovedメソッドの戻り値がtrueの間`とかはどうでしょう

あと`forward`と`backward`のbriefが全く同じなので
`動く`を`前進する`と`後進する`にそれぞれ変更したほうがいい気がします

2019-06-13 09:53 UTC, Oiwane commented on src/module/Navigator.cpp
> +bool Navigator::isMoved(int goalDistance, bool isForward)
`isMoved`よりも`hasArrived`のほうが良いと思いました

2019-06-13 09:53 UTC, Oiwane commented on src/module/Navigator.h
> +  bool isMoved(int goalDistance, bool isForward);
`isMoved`よりも`hasMoved`のほうが良いと思いました

2019-06-13 09:53 UTC, Oiwane commented on src/module/Navigator.cpp
> +  while(isMoved(goalDistance, true)) {
`isMoved`よりも`hasArrived`のほうが良いと思いました

2019-06-13 09:53 UTC, Oiwane commented on src/module/Navigator.cpp
> +  while(isMoved(goalDistance, false)) {
`isMoved`よりも`hasArrived`のほうが良いと思いました

2019-06-13 10:22 UTC, korosuke613 commented
![image](https://user-images.githubusercontent.com/20027695/59425282-87c58300-8e10-11e9-899f-a6be2fca1b4d.png)

テストが失敗しているね
なんでだろう？

2019-06-15 07:53 UTC, arimakaoru commented
#89 「Controllerクラスにモーター制御のクラスを追加する」がマージされると、`controller.leftWheel`、`controller.rightWheel`は使用できなくなります。

代わりにControllerクラスのメンバ関数
 `getLeftMotorCount`
 `getRightMotorCount`
 `setLeftMotorPwm`
 `setRightMotorPwm`
を使いましょう。

2019-06-15 08:07 UTC, korosuke613 commented
いや、#89 がmergeされるまではこのままでいい

2019-06-16 00:11 UTC, arimakaoru approved these changes

2019-06-16 11:34 UTC, Oiwane approved these changes

2019-06-16 11:35 UTC, merged